### ISSUE TITLE
BaseRequest.java:464-470: Implement and unit test method...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#10]
The puzzle `87-bd2cb401` from #87 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/6ac89f6b4b4259595415f14fbfd8bfe53b0478ef/src/main/java/com/amihaiemil/docker/BaseRequest.java#L464-L470

The puzzle was created by Mihai Andronache on 28-Jan-18. 

Estimate: 60 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by amihaiemil** [comment]
this is invalid, the puzzle should be removed at the next push.

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
