### ISSUE TITLE
SslHttpClient.java:50-52: Using the provided...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#100]
The puzzle `67-80672d59` from #67 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/873268efb61ad61f0d508acc00f355ea9cf948d1/src/main/java/com/amihaiemil/docker/SslHttpClient.java#L50-L52

The puzzle was created by amihaiemil on 08-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#100](https://github.com/amihaiemil/docker-java-api/issues/100) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#100](https://github.com/amihaiemil/docker-java-api/issues/100) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1310652873); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by amihaiemil** [comment]
@llorllale This is a rather complex task. The big outline is that we need to first read the contents of the certificates, then use them to create objects of type KeyStore and such (from the JDK), which will go to some Factory from Apache -- that's how the guys from Spotify did it [here](https://github.com/spotify/docker-client) but if you have a better idea, feel free to say it. This, of course, can be a research task as well :D

**Comment by llorllale** [comment]
@amihaiemil this here...

```java
    /**
     * Ctor.
     * @param certs Path to the folder containing the following certificates:
     *  ca.pem, cert.pem and key.pem.
     */
    SslHttpClient(final Path certs, final char[] passwd) {
```

Is `cert.pem` the docker server's public key?

**Comment by llorllale** [comment]
@0crat waiting

**Comment by amihaiemil** [comment]
@llorllale 

> Is cert.pem the docker server's public key?

Yes, I think so, param ``Path certs`` points to a folder containing the following certificates: ca.pem, cert.pem and key.pem. ``key`` is the private key and I assume ``cert`` is the public one. These 3 are created when you create a remote docker host using ``dockermachine``.

I assume you spent the time researching (or more, let me know if so). So just edit the puzzle with the resources that you found :D

**Comment by llorllale** [comment]
@amihaiemil is this supposed to be two-way or one-way tls?

**Comment by amihaiemil** [comment]
@llorllale two-way, that's my understanding, since we don't have other authentication mechanism between the ``docker`` client and the remote docker host.

**Comment by llorllale** [comment]
@amihaiemil and is `ca.pem` the server's public key? I'm confused because "ca" sounds like "certificate authority", which would definitely not be docker.

**Comment by amihaiemil** [comment]
@llorllale yes, I think it is the server's public key as well. 

``ca.pem`` - server public key (the server's public key issues by the CA, right? I think that's why the name is ``ca.pem``
``cert.pem`` - client certificate
``key.pem`` - client key

**Comment by llorllale** [comment]
@0crat waiting for review/merge on #120

**Comment by 0crat** [comment]
> @0crat waiting for review/merge on #120 ([here](https://github.com/amihaiemil/docker-java-api/issues/100#issuecomment-391734513))

@llorllale Job [#100](https://github.com/amihaiemil/docker-java-api/issues/100) is already on hold

**Comment by amihaiemil** [comment]
@0crat boost 6x

**Comment by 0crat** [comment]
> @0crat boost 6x ([here](https://github.com/amihaiemil/docker-java-api/issues/100#issuecomment-391949141))

@amihaiemil Boost 6x was set for [#100](https://github.com/amihaiemil/docker-java-api/issues/100)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)
