### ISSUE TITLE
Image.java:37-39: Finish implementing the operations that...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#103]
The puzzle `96-6bad42df` from #96 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/d253105e7e20178d649b8c463cee5c9fc01b13f0/src/main/java/com/amihaiemil/docker/Image.java#L37-L39

The puzzle was created by Mihai A on 10-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#103](https://github.com/amihaiemil/docker-java-api/issues/103) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#103](https://github.com/amihaiemil/docker-java-api/issues/103) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1310653954); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by llorllale** [comment]
@amihaiemil this one should've been closed when #112 was merged

**Comment by amihaiemil** [comment]
@llorllale I see. There were some issues with ``0pdd`` these days, I opened an Issue about it this morning.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#103](https://github.com/amihaiemil/docker-java-api/issues/103) is now out of scope
