### ISSUE TITLE
URL encode the query parameters

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#109]
We need to make sure the query parameters are encoded properly, otherwise exceptions are thrown as seen [here](https://travis-ci.org/amihaiemil/docker-java-api/jobs/379218662#L1959).

**Comment by 0crat** [comment]
Job [#109](https://github.com/amihaiemil/docker-java-api/issues/109) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#109](https://github.com/amihaiemil/docker-java-api/issues/109) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1351440349); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat waiting for review/merge on #119

**Comment by 0crat** [comment]
> @0crat waiting for review/merge on #119 ([here](https://github.com/amihaiemil/docker-java-api/issues/109#issuecomment-391461302))

@llorllale The impediment for [#109](https://github.com/amihaiemil/docker-java-api/issues/109) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#109](https://github.com/amihaiemil/docker-java-api/issues/109) is now out of scope
