### ISSUE TITLE
LocalDocker and RemoteDocket

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#11]
There will be 2 implementations of Docker: 
    
1.  ``LocalDocker``, working through a UnixSocket request, connected to the local docker daemon
2.  ``RemoteDocker``, working thorugh an tcp request, connected to a remove docker daemon.

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#67](https://github.com/amihaiemil/docker-java-api/issues/67), [#68](https://github.com/amihaiemil/docker-java-api/issues/68) are still not solved; solved: [#23](https://github.com/amihaiemil/docker-java-api/issues/23), [#24](https://github.com/amihaiemil/docker-java-api/issues/24).

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#100](https://github.com/amihaiemil/docker-java-api/issues/100), [#68](https://github.com/amihaiemil/docker-java-api/issues/68) are still not solved; solved: [#23](https://github.com/amihaiemil/docker-java-api/issues/23), [#24](https://github.com/amihaiemil/docker-java-api/issues/24), [#67](https://github.com/amihaiemil/docker-java-api/issues/67).
