### ISSUE TITLE
abstract JsonResource implements JsonObject

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#114]
Let's make this abstract implementation of JsonObject which will be extended by:

 * ``Inspection``
 * ``RtContainer``, ``RtImage`` and any other Json resource/entity returned by the API (``Container``, ``Image`` and other resource interfaces will extend ``JsonObject``

RtContainer and others will pass their JsonObject representation to the ``super`` JsonResource.

This change is needed in order to have more polymorphism and also to avoid the N+1 query problem as much as possible.

**Comment by 0crat** [comment]
The job [#114](https://github.com/amihaiemil/docker-java-api/issues/114) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1371012325); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#114` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#114](https://github.com/amihaiemil/docker-java-api/issues/114) is now out of scope
