### ISSUE TITLE
Image.run(...)

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#127]
Image should have the ``run`` option, and return the created Container. This will be the equivalent of the ``docker run IMAGE`` command.

**Comment by 0crat** [comment]
Job [#127](https://github.com/amihaiemil/docker-java-api/issues/127) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat wait while I try to understand something...

**Comment by 0crat** [comment]
> @0crat wait while I try to understand something... ([here](https://github.com/amihaiemil/docker-java-api/issues/127#issuecomment-395089574))

@llorllale The impediment for [#127](https://github.com/amihaiemil/docker-java-api/issues/127) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@amihaiemil seems like the JSONs holding the image's metadata don't have a dedicated "name" field. The closest thing I see that we could use is `RepoTags`, but it's an array. Eg.:

```json
"RepoTags": [
    "example:1.0",
    "example:latest",
    "example:stable"
]
```
Is the first half of those values always the same?

**Comment by amihaiemil** [comment]
@llorllale Yes, I also noticed that, but we add the ``Name`` ourselves, when pulling the image, see [here](https://github.com/amihaiemil/docker-java-api/blob/30319f5e9d345f8c757ae003c88c38e6fc4955ae/src/main/java/com/amihaiemil/docker/RtImages.java#L82)

Also, the name of the image is in its URI, as the last segment (but better take it from the Json).

Is this what you asked? :D

**Comment by llorllale** [comment]
@amihaiemil 

Well, yes, but there's no guarantee that it'll be constant.

I just tested:

```C:\> docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
alpine                           latest              3fd9065eaf02        5 months ago        4.15MB
```
```
C:\> docker tag alpine docker-java-api
```
```C:\> docker images
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
alpine                           latest              3fd9065eaf02        5 months ago        4.15MB
docker-java-api                  latest              3fd9065eaf02        5 months ago        4.15MB
```

And resulting inspection for `alpine` reveals:

```json
        "RepoTags": [
            "alpine:latest",
            "docker-java-api:latest"
        ]
```

**Comment by amihaiemil** [comment]
@llorllale I see, but you don't really need that, do you? Since the name is in the Json (we append it manually when pulling the image) and URI anyay. Or you mean something else?

**Comment by llorllale** [comment]
@amihaiemil as far as I can see, there is no `docker run <image>` equivalent in the [docker api](https://docs.docker.com/engine/api/v1.35/#tag/Image). So I figured this new `Image.run()` that you're asking for would be a shortcut for `Containers.create(image); Container.start();`. Or am I wrong?

**Comment by amihaiemil** [comment]
@llorllale Yes, exactly, and since RtImage has the name of the Image, it can somehow instantiate RtContainers and create and start a container using its name.

And Image will get the Containers instance from the encapsulated Docker instance -- I also want to implement this: any object of the API should have a method to return its parent Docker instance. So Image.run would look something like this (pseudocode):

```java
final Container ctn = this.docker.containers.create(this.name);
ctn.start();
return ctn;
```

Do you like the idea? Maybe you can start by passing the Docker instance to RtImage and have public method ``docker()``?

**Comment by llorllale** [comment]
@amihaiemil 

> Maybe you can start by passing the Docker instance to RtImage and have public method docker()?

Sure.

Now back to my original question.

> the name of the image is in its URI, as the last segment (but better take it from the Json)

As I've shown, `RepoTags` is not really reliable, so I believe the better alternative is to take it from the URI. Do you agree?

**Comment by amihaiemil** [comment]
@llorllale Yes, I think the URI is the safest, go with that.

**Comment by llorllale** [comment]
@0crat waiting for review/merge of PR #140

**Comment by 0crat** [comment]
> @0crat waiting for review/merge of PR #140 ([here](https://github.com/amihaiemil/docker-java-api/issues/127#issuecomment-398508346))

@llorllale Job [#127](https://github.com/amihaiemil/docker-java-api/issues/127) is already on hold

**Comment by amihaiemil** [comment]
@0crat boost x6

**Comment by 0crat** [comment]
> @0crat boost x6 ([here](https://github.com/amihaiemil/docker-java-api/issues/127#issuecomment-398653475))

@amihaiemil Argument "x6" doesn't match regex `\d+x`

**Comment by amihaiemil** [comment]
@0crat boost 6x

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@095c162d-96f5-4418-a96c-3a3627c066c0, thread: pool-1135-thread-1
java.util.concurrent.ThreadPoolExecutor$AbortPolicy[2063] java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@48f2798a rejected from java.util.concurrent.ThreadPoolExecutor@7e91cbd3[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2432938]
```

[0.22.6](https://github.com/zerocracy/farm): Issue: amihaiemil/docker-java-api#127, Comment: 398654937

**Comment by amihaiemil** [comment]
@0crat boost 6x

**Comment by 0crat** [comment]
> @0crat boost 6x ([here](https://github.com/amihaiemil/docker-java-api/issues/127#issuecomment-398657514))

@amihaiemil Boost 6x was set for [#127](https://github.com/amihaiemil/docker-java-api/issues/127)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a0cc108b-284c-417e-b3b4-360e68d85261, thread: AsyncFlush-7
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "verbosity/llorllale.xml" in "PMO" in 2min: a3e35cd2a8c4/18s/0/2/true/false by QuartzScheduler_Worker-3
```

[0.22.22](https://github.com/zerocracy/farm): CID: [1720734113](https://www.0crat.com/G6LPQQV2P/1720734113), Type: "Close job", Author: "amihaiemil"

**Comment by 0crat** [comment]
The job [#127](https://github.com/amihaiemil/docker-java-api/issues/127) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1722003014); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by llorllale** [comment]
@amihaiemil can this be taken out of scope?

**Comment by amihaiemil** [comment]
@0crat out

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/amihaiemil/docker-java-api/issues/127#issuecomment-399534705))

@amihaiemil The job [#127](https://github.com/amihaiemil/docker-java-api/issues/127) is now out of scope
