### ISSUE TITLE
Continue implementing Logs

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#130]
0pdd should have created an Issue for this. Remove the ``todo`` when done.

**Comment by 0crat** [comment]
The job [#130](https://github.com/amihaiemil/docker-java-api/issues/130) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1570597575); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#130` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@0crat waiting for release

**Comment by 0crat** [comment]
> @0crat waiting for review ([here](https://github.com/amihaiemil/docker-java-api/issues/130#issuecomment-396155758))

@amihaiemil The impediment for [#130](https://github.com/amihaiemil/docker-java-api/issues/130) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#130](https://github.com/amihaiemil/docker-java-api/issues/130) is now out of scope

**Comment by amihaiemil** [comment]
@0crat footprint

**Comment by 0crat** [comment]
> @0crat footprint  ([here](https://github.com/amihaiemil/docker-java-api/issues/130#issuecomment-414115887))

@amihaiemil Can't understand "footprint", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/amihaiemil/docker-java-api/issues/130#issuecomment-414116522))

@amihaiemil This is what I know about this job in G6LPQQV2P, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#130](https://github.com/amihaiemil/docker-java-api/issues/130) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/G6LPQQV2P?q=%7Bjob%3A%27gh%3Aamihaiemil%2Fdocker-java-api%23130%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by zoeself** [comment]
@andronachev thank you for resolving this ticket. I've just added it to your active invoice. You can alwayscheck all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
