### ISSUE TITLE
Implement logs.fetch()

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#135]
Continue with logs.fetch(). Again, 0pdd is down, modify the puzzle in the code after finishing.

**Comment by 0crat** [comment]
The job [#135](https://github.com/amihaiemil/docker-java-api/issues/135) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1631261695); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#135` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#135](https://github.com/amihaiemil/docker-java-api/issues/135) is now out of scope
