### ISSUE TITLE
Add save/export functionality to the API

### ISSUE THREAD

**Issue by thomas-melville** [amihaiemil/docker-java-api#144]
Hi,

I would like to update the API to include the functionality to save/export several images to a tar ball
https://docs.docker.com/engine/api/v1.30/#operation/ImageGetAll

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@thomas-melville[/z](https://www.0crat.com/u/thomas-melville) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by thomas-melville** [comment]
@amihaiemil no, not yet. I will read them and read through the code.

Yes, I agree that the InputStream should be returned and the user handle it however they like, just like the command line.
Yes I see, through encapsulation of the iteration.
Sounds good.

**Comment by amihaiemil** [comment]
@thomas-melville I will start with this functionality as it will involve some redesign of the code (I imagine ``RtImages`` will become abstract, for instance). I'll do it this week sometime, when I find some free slot for it. Then, when the design is clear, you can proceed with the rest. 

Keep in mind that PRs to this repo should be small (ideally, 30min of work tops). We are using xdsd.org and [Puzzle Driven Development](https://www.yegor256.com/2010/03/04/pdd.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/amihaiemil/docker-java-api/issues/144#issuecomment-406808873))

@amihaiemil The impediment for [#144](https://github.com/amihaiemil/docker-java-api/issues/144) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@thomas-melville I started with the redesigned and left puzzles for continuing implementation, including that ``save()`` method.

Again, ``save()``, should work on any given implementation of ``Images``, be it listed, searched, filtered, double-filtered or maybe even the history of an ``Image`` (which will also be an instance of ``Images``, I think)

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#144](https://github.com/amihaiemil/docker-java-api/issues/144) is now out of scope

**Comment by thomas-melville** [comment]
Thanks @amihaiemil
