### ISSUE TITLE
Appears inspect() is putting an extra set of double quotes around strings (?)

### ISSUE THREAD

**Issue by rwmajor2** [amihaiemil/docker-java-api#150]
When I inspect an Image, looking for a repo, it appears it has an extra set of double quotes in the actual string:

![image](https://user-images.githubusercontent.com/3799165/44272519-15454000-a20b-11e8-8096-874ec513137f.png)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@rwmajor2[/z](https://www.0crat.com/u/rwmajor2) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@rwmajor2 That is most likely a trick played by the IDE, or maybe the String comes like that from Docker? We certainly don't add any quotes of our own.

``RtImage.inspect()`` returns an ``Inspection``, which is a JsonObject (spec. compliant) -- Inspection, on the other hand, fetches the Json from the API and uses class [ReadJsonObject](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/ReadJsonObject.java) which is an Apache ResponseHandler that simply parses the Http Response into a JsonObject.

**Comment by amihaiemil** [comment]
@rwmajor2 I will close this, as I there is nothing to do about it.

If you the strings are indeed double-quoted, try changing the JSON-P provider (although I tried both glassfish and redhat and never had this problem). But, again, I think it's just a display problem in the IDE :)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#150` is not assigned, can't get performer
