### ISSUE TITLE
Add Images.save()

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#152]
This method should save the given ``Images`` into a tarball and return the ``InputStream``. See [puzzle](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/Images.java#L46)

**Comment by 0crat** [comment]
Job [#152](https://github.com/amihaiemil/docker-java-api/issues/152) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#152` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#152](https://github.com/amihaiemil/docker-java-api/issues/152) is now out of scope
