### ISSUE TITLE
Add Images.filter(...)

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#153]
See [puzzle](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/Images.java#L39)

**Comment by 0crat** [comment]
Job [#153](https://github.com/amihaiemil/docker-java-api/issues/153) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#153](https://github.com/amihaiemil/docker-java-api/issues/153) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/2481052540); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat wait because I submitted PR #160 for this

**Comment by 0crat** [comment]
> @0crat wait because I submitted PR #160 for this ([here](https://github.com/amihaiemil/docker-java-api/issues/153#issuecomment-428409703))

@llorllale The impediment for [#153](https://github.com/amihaiemil/docker-java-api/issues/153) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by amihaiemil** [comment]
@0crat boost 6x

**Comment by 0crat** [comment]
> @0crat boost 6x ([here](https://github.com/amihaiemil/docker-java-api/issues/153#issuecomment-429729244))

@amihaiemil Boost 6x was set for [#153](https://github.com/amihaiemil/docker-java-api/issues/153)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#153](https://github.com/amihaiemil/docker-java-api/issues/153) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +90 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)
