### ISSUE TITLE
Continue filtering in ListedImages

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#154]
See [puzzle](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/ListedImages.java#L38).

**Comment by 0crat** [comment]
Job [#154](https://github.com/amihaiemil/docker-java-api/issues/154) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#154](https://github.com/amihaiemil/docker-java-api/issues/154) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/2471844556); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@llorllale Yes, pretty much... I looked over this once, a few weeks ago, and I think I came to the conclusion one of these tasks is obsolete. Could you refuse it until I figure it out? These days I am also rather busy and do not have as much time for OSS :(

**Comment by llorllale** [comment]
@amihaiemil do you think there is a more elegant way forward than just overloading the `Docker.images()` method?

**Comment by amihaiemil** [comment]
@llorllale 

> do you think there is a more elegant way forward than just overloading the Docker.images() method?

I'm not sure what you mean by this :D 
In this ticket we should add a Map of filters to the class ``ListedImages``. The class should remain immutable, only add filters via the ctor -- that is, from ``Image.filter(...)`` we will simply ``new ListedImages(..., modifiedMap);``. So actually this ticket and #153 are not the same thing. 

I wanted to find a more elegant way since, like this, we will have that filtering map duplicated accross different implementations of ``Images``... sadly, I couldn't come up with a suitable solution, so I say we do it like this and maybe decide on refactoring in the future. 

Makes sense? :D

**Comment by llorllale** [comment]
@amihaiemil I see.

So you want the solution to look like:

```java 
docker.images().filter(...) -> Images
```

.. instead of:

```java
docker.images(filter) -> Images
```

**Comment by llorllale** [comment]
@amihaiemil I think your solution is semantically inconsistent.

I would expect `docker.images().filter(...)` to also be reflected on the `docker.images()` instance that I already possess. Kinda weird, don't you think?

**Comment by amihaiemil** [comment]
@llorllale The initial ``Images`` you get from ``docker.images()`` basically contains all the images, with no filters applied. Then, if you want to apply some filters, you use ``Images.filter(...)``.

And, if you call ``.filter(...)`` multiple times, the final ``Images`` instance will indeed respect all of them. Passing the map of filters to the ``docker.images(...)`` method has 2 problems IMO:

1. you oblige the user to pass a Map (even an empty one) from the start, or you have to overload ``.images()``

2. SRP is a bit broken since now ``Docker`` knows something about filtering, which it is not supposed to. The docker client shouldn't care if the Images, Containers etc can or cannot be filtered.

3. Filrering multiple times will cause procedural code for the client since they will have to manually fetch the existing filters of the ``Images`` they got, iterate over them and put them in a new Map, together with the new filters, which they will pass again to ``docker.images(...)``

Makes sense? :D

**Comment by llorllale** [comment]
@amihaiemil sure, it makes sense, it's just that it would've been nice if we could do

```java
new Filter(
    docker.images()
);
```

And have an implementation smart enough to not fetch all images from the docker registry and then filter them in-memory.

But ok, let's not dwell to much and go forward with this.

**Comment by llorllale** [comment]
@0crat wait because I submitted PR #159 for this

**Comment by 0crat** [comment]
> @0crat wait because I submitted PR #159 for this ([here](https://github.com/amihaiemil/docker-java-api/issues/154#issuecomment-425654330))

@llorllale Job [#154](https://github.com/amihaiemil/docker-java-api/issues/154) is already on hold

**Comment by amihaiemil** [comment]
@0crat boost 6x

**Comment by 0crat** [comment]
> @0crat boost 6x ([here](https://github.com/amihaiemil/docker-java-api/issues/154#issuecomment-426543909))

@amihaiemil Boost 6x was set for [#154](https://github.com/amihaiemil/docker-java-api/issues/154)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Order was finished: +90 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#154](https://github.com/amihaiemil/docker-java-api/issues/154) is now out of scope
