### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by rwmajor2** [amihaiemil/docker-java-api#158]
Hi @amihaiemil.  I have a question.  We are thinking about using this API for a product I am building and you will see me become active with some PRs.  :)  

My question relates to the BSD-3 license and my lack of understanding in this area.  If I wanted to incorporate this into my Java project, am I supposed to keep the `com.amihaiemil.docker` package name and use it as a separate dependency?  Or can I bring this API into my Java project and have the package get renamed so its appropriate within my project, e.g. `com.myproject.simpledockerapi`?

Thanks for any info.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@rwmajor2[/z](https://www.0crat.com/u/rwmajor2) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by rwmajor2** [comment]
@amihaiemil Awesome.  Thanks for the clarification.  I will likely keep it as a separate project so I can easily submit PRs back.  But, IF I wanted to bring it into my own Java project (and package names), then nothing prevents that from a license perspective as long as I keep your header comments.  Corr

**Comment by amihaiemil** [comment]
@rwmajor2 Sure, there is no problem from the Licence's point of view, as long as you keep the header comments. :)

**Comment by amihaiemil** [comment]
@rwmajor2 About PRs, a few points:

1. Before making a PR, open an Issue about the bug of feature requests you have in mind, so we can discuss.

2. Please make sure you and/or your colleagues understand this library's architecture before submitting any PR. 

3. Small PRs, ideally maximum 5 changed files, including tests. 

4. If you expect to rely on this library a lot (e,g, you expect to make many PRs and want to move fast), keep in mind that these days I am a bit busier (started an MSc degree), so I may not respond so quickly... I'll do my best, but as mentioned in the first comment, I can't guarantee anything.

**Comment by rwmajor2** [comment]
I appreciate your notes.  We are really planning to only use this API for < 10 Docker api calls so any PRs will focus around capability that hasn't been built in yet.

**Comment by amihaiemil** [comment]
@rwmajor2 If this topic is clear, I'll close this issue. Feel free to open others if there are more questions :D

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#158` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
