### ISSUE TITLE
Option to show all containers, not only running ones

### ISSUE THREAD

**Issue by wem** [amihaiemil/docker-java-api#161]
First, very simple, small lib!
It would be nice to make it possible to query for all containers, not only the running one (with the "all" query param)

**Comment by 0crat** [comment]
Thanks for your contribution, @wem[/z](https://www.0crat.com/u/wem)! If you would be a member of [the project](https://www.0crat.com/p/G6LPQQV2P), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#161](https://github.com/amihaiemil/docker-java-api/issues/161) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/5183b7c3-6d25-4e93-9d62-9ba338dd869b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#161` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by wem** [comment]
@amihaiemil Container.all() would be a nice solution!
I will think about to join this project

**Comment by amihaiemil** [comment]
@wem thanks, I'm on it just now :)

**Comment by amihaiemil** [comment]
@rultor let's release it, tag is `0.0.4`

**Comment by amihaiemil** [comment]
@wem Done, version ``0.0.4`` is released, you should already be able to pull it with maven (see README for updated coordinates). 

Could you please close this Issue? I think the PM will complain if I do it :(

**Comment by 0crat** [comment]
Job was finished in 9 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#161](https://github.com/amihaiemil/docker-java-api/issues/161) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)
