### ISSUE TITLE
Depend on JSON-P API instead of Glassfish implementation

### ISSUE THREAD

**Issue by daniel-shuy** [amihaiemil/docker-java-api#163]
Since you expect projects that depend on this library to provide a [JSON-P (JSR 374)](https://javaee.github.io/jsonp/index.html) implementation, your Maven POM should depend on the [JSON-P API](https://mvnrepository.com/artifact/javax.json/javax.json-api) instead of a specific implementation.

Even though the Glassfish implementation is the reference implementation, it may have some concrete implementations that is not in the specification that your library may inadvertently depend on in a future version, which will break if a project provides a different JSON-P implementation.

**Comment by 0crat** [comment]
Thanks for your contribution, @daniel-shuy[/z](https://www.0crat.com/u/daniel-shuy)! If you would be a member of [the project](https://www.0crat.com/p/G6LPQQV2P), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#163](https://github.com/amihaiemil/docker-java-api/issues/163) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/704419a1-2c5e-4e5b-8c31-0c491389fb1c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#163` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@daniel-shuy PR #164 has been merged. Can you please close this issue? If I do it, the PM will complain.

**Comment by daniel-shuy** [comment]
Wow that was fast!

> @daniel-shuy hmmm, but we do need one implementation for test purposes, otherwise the tests will fail. I guess the most correct would be the following:
> 
> 1. Have the JSON-P api dependency with scope  `provided`
> 2. Have the Glassfish impl dependency with scope `test`
> 
> Right? WDYT?

Wow that was fast! Yeah that's the right way to do it.

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#163](https://github.com/amihaiemil/docker-java-api/issues/163) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)
