### ISSUE TITLE
Expose the HttpClient

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#165]
``Docker`` should have the ``HttpClient :: httpClient()`` method to return the underlying Apache http client. 

This is in order to provide some extensibility -- the user should be able to make raw HTTP calls to Docker's API in case the library does not yet provide the API method in question. This is especially important in the case of ``LocalDocker`` for which the HttpClient is quite hard to configure (it needs to use unix sockets).

Apache's ``HttpClient`` object is immutable so there should not be any danger in exposing it.

**Comment by 0crat** [comment]
The job [#165](https://github.com/amihaiemil/docker-java-api/issues/165) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/b7f695ee-5669-4972-9384-44fe8b3626df); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@rultor release it, tag is `0.0.5`

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)
