### ISSUE TITLE
Continue with Volumes API

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#169]
See API description [here](https://docs.docker.com/engine/api/v1.37/#tag/Volume).

See [contributing guidelines](https://github.com/amihaiemil/docker-java-api/blob/master/CONTRIBUTING.md). Also, [this](https://www.yegor256.com/2014/04/15/github-guidelines.html) might be helpful.

**Comment by amihaiemil** [comment]
@maviteixeira Thank you for the contribution! Are you a member of Zerocracy, do you want me to invite you to this project and continue making PRs? Please note, however, that we don't have any funds at the moment, so there will be no payments unfortunately.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#169` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
