### ISSUE TITLE
Auth.java:34-36: Implement a new auth named 'Token' that...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#171]
The puzzle `99-9320c256` from #99 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/ab0d78ec783de53306d63a66dd459598d58dc8c4/src/main/java/com/amihaiemil/docker/Auth.java#L34-L36

The puzzle was created by rultor on 23-May-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#171](https://github.com/amihaiemil/docker-java-api/issues/171) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#171](https://github.com/amihaiemil/docker-java-api/issues/171) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/826bca7d-5dfd-4cee-998e-4ce2b9e72b17); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat wait because I submitted PR #188 for this

**Comment by 0crat** [comment]
> @0crat wait because I submitted PR #188 for this ([here](https://github.com/amihaiemil/docker-java-api/issues/171#issuecomment-437681751))

@llorllale The impediment for [#171](https://github.com/amihaiemil/docker-java-api/issues/171) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `99-9320c256` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
