### ISSUE TITLE
RemoteDocker.java:39-41: Implement integration tests for...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#178]
The puzzle `68-39eec482` from #68 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/ab0d78ec783de53306d63a66dd459598d58dc8c4/src/main/java/com/amihaiemil/docker/RemoteDocker.java#L39-L41

The puzzle was created by rultor on 23-May-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#178](https://github.com/amihaiemil/docker-java-api/issues/178) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#178](https://github.com/amihaiemil/docker-java-api/issues/178) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/0a4cb78d-a482-4fe1-8f18-4114cc586971); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@llorllale thank you for your idea. I will have a look over the weekend and also over your PRs (too busy week now, sorry).

**Comment by 0crat** [comment]
The job [#178](https://github.com/amihaiemil/docker-java-api/issues/178) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/e1490b0a-d2bf-4ec1-b7ef-e6900a8cbe83); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/amihaiemil/docker-java-api/issues/178#issuecomment-444000052))

@amihaiemil GitHub issue is still open, won't close

**Comment by amihaiemil** [comment]
@bkuzmic I see, thank you for your input. It's enough for now, I'll have a look later. I'll remove the puzzle so this task is closed :D

**Comment by 0pdd** [comment]
The puzzle `68-39eec482` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@49da8b6e-a0bd-48c7-a0cd-3edbad03b45d, thread: AsyncProc-5
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:amihaiemil/docker-java-api#178] declared for identity constraint of element "verbosity".
```

[0.38.6](https://github.com/zerocracy/farm): CID: [10ae4b62-b189-48e7-9d6e-8661c99aa370](https://www.0crat.com/footprint/G6LPQQV2P/10ae4b62-b189-48e7-9d6e-8661c99aa370), Type: "Close job"

**Comment by 0crat** [comment]
Job was finished in 18 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
