### ISSUE TITLE
Volume.java:34: Continue the implementation of Volume.

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#191]
The puzzle `169-c2961002` from #169 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/f2b7c203dcd213923b095b276cc9f62ae5a25928/src/main/java/com/amihaiemil/docker/Volume.java#L34-L34

The puzzle was created by unstablemark on 19-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#191](https://github.com/amihaiemil/docker-java-api/issues/191) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#191](https://github.com/amihaiemil/docker-java-api/issues/191) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/f6ed9c27-c7f7-41cc-878c-414521f4f76d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `169-c2961002` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
