### ISSUE TITLE
Auth.java:34-36: We have implemented all forms of Auth....

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#193]
The puzzle `171-ffb27b82` from #171 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/f3a8549c161697f3f04488eca7742c5ba97bda5f/src/main/java/com/amihaiemil/docker/Auth.java#L34-L36

The puzzle was created by rultor on 27-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#193](https://github.com/amihaiemil/docker-java-api/issues/193) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#193](https://github.com/amihaiemil/docker-java-api/issues/193) assigned to @sbespalov[/z](https://www.0crat.com/u/sbespalov), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/d83aafc3-e112-4666-a3a8-be59798b9bbf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@sbespalov[/z](https://www.0crat.com/u/sbespalov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by sbespalov** [comment]
> Figure out how to make the library decorate the base HttpClient with the AuthHttpClient in a seemless manner. 

This can be done in the form of DSL builder. Something like below:
```
DockerApiBuilder dockerApiBuilder = new DockerApiBuilder();
Docker docker = dockerApiBuilder
// this will create `LocalDocker`
.local()
// this will use `Credentials` authentication
.auth().credentials("user","password")
.build();
```

**Comment by sbespalov** [comment]
@amihaiemil this will be enough for the issue?

**Comment by amihaiemil** [comment]
@sbespalov hmm, I don't like Builders :)

I want the user to simply instantiate a ``Docker`` instance via the ``new`` operator (with ``RemoteDocker`` or ``LocalDocker``). For now just add the ``Credentials`` parameter to [this](https://github.com/amihaiemil/docker-java-api/blob/11e0632fb81b4cb49690162a443c3581365b5d35/src/main/java/com/amihaiemil/docker/RemoteDocker.java#L83) constructor and decorate the ``PlainHttpClient`` with [AuthHttpClient](https://github.com/amihaiemil/docker-java-api/blob/49e9cb18f0a8d2da9e9e0bc5604dd8047d689ba5/src/main/java/com/amihaiemil/docker/AuthHttpClient.java). 

I don't think this will be enough to cover all the authentication flows, but we'll see later on (I still have to study the topic, I didn't work on it at all) :) 

Don't forget to remove the ``todo`` from the code.

**Comment by 0pdd** [comment]
The puzzle `171-ffb27b82` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#193](https://github.com/amihaiemil/docker-java-api/issues/193) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @sbespalov[/z](https://www.0crat.com/u/sbespalov)
