### ISSUE TITLE
Implement docker system commands

### ISSUE THREAD

**Issue by bkuzmic** [amihaiemil/docker-java-api#194]
Implement docker system commands as in docs:
https://docs.docker.com/engine/reference/commandline/system/

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@bkuzmic I think you are referring to the [System API](https://docs.docker.com/engine/api/v1.37/#tag/System). Yes, it makes sense :)

**Comment by 0crat** [comment]
Job [#194](https://github.com/amihaiemil/docker-java-api/issues/194) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
The job [#194](https://github.com/amihaiemil/docker-java-api/issues/194) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/f40c3ede-a689-47b5-94cd-03338e482456); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@0crat boost 6x

**Comment by 0crat** [comment]
> @0crat boost 6x ([here](https://github.com/amihaiemil/docker-java-api/issues/194#issuecomment-444009178))

@amihaiemil Boost 6x was set for [#194](https://github.com/amihaiemil/docker-java-api/issues/194)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@49da8b6e-a0bd-48c7-a0cd-3edbad03b45d, thread: AsyncProc-7
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:amihaiemil/docker-java-api#194] declared for identity constraint of element "verbosity".
```

[0.38.6](https://github.com/zerocracy/farm): CID: [3a48f212-5477-4eac-bd49-2b668dd9922b](https://www.0crat.com/footprint/G6LPQQV2P/3a48f212-5477-4eac-bd49-2b668dd9922b), Type: "Close job"

**Comment by 0crat** [comment]
Job was finished in 19 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#194](https://github.com/amihaiemil/docker-java-api/issues/194) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +95 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
