### ISSUE TITLE
Subclasses of JsonResource are susceptible to violate the LSP

### ISSUE THREAD

**Issue by victornoel** [amihaiemil/docker-java-api#202]
The methods in `JsonResource` should be final in order to forbid subclasses to modify them and potentially violate the Liskov Substitution Principle.

**Comment by 0crat** [comment]
Job [#202](https://github.com/amihaiemil/docker-java-api/issues/202) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#202](https://github.com/amihaiemil/docker-java-api/issues/202) assigned to @sbespalov[/z](https://www.0crat.com/u/sbespalov), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/8def7f73-4990-4f45-a474-464a9b3b304a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
@sbespalov[/z](https://www.0crat.com/u/sbespalov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by sbespalov** [comment]
@0crat close

**Comment by amihaiemil** [comment]
@victornoel issue is fixed, pleade clode this :)

**Comment by 0crat** [comment]
> @0crat close ([here](https://github.com/amihaiemil/docker-java-api/issues/202#issuecomment-447330291))

@sbespalov Can't understand "close", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by victornoel** [comment]
@amihaiemil @sbespalov yep, thanks :)

**Comment by 0crat** [comment]
The job [#202](https://github.com/amihaiemil/docker-java-api/issues/202) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @sbespalov[/z](https://www.0crat.com/u/sbespalov)
