### ISSUE TITLE
Use qulice checks instead of checkstyle

### ISSUE THREAD

**Issue by paulodamaso** [amihaiemil/docker-java-api#204]
Currently we are just using `checkstyle` for static analisys, we should use `qulice` which provides `PMD` and `findbugs` checks besides `checkstyle`  ones

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@paulodamaso Thanks for the suggestion, I had thought about it in the past but I decided to skip ``qulice``. It is too strict, absurdly strict. I believe ``checkstyle`` is enough :)

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#204` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
