### ISSUE TITLE
Volume.java:38: Continue implementing create and remove...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#205]
The puzzle `179-c7050a34` from #179 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/5a8ab3e28f16be28a57f8be1044416450b22f765/src/main/java/com/amihaiemil/docker/Volume.java#L38-L38

The puzzle was created by Boris Kuzmic on 06-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#205](https://github.com/amihaiemil/docker-java-api/issues/205) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/97a8327b-d699-4f71-9eb7-7b12e955423f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by bkuzmic** [comment]
@amihaiemil This issue should have closed automatically, right?

**Comment by amihaiemil** [comment]
@bkuzmic yes, 0pdd closes tickets automatically, but only if you remove the ``todo``. You forgot to remove it :) 

I'll remove it now.

**Comment by amihaiemil** [comment]
@bkuzmic Actually, I see you removed it. It's funny, it should have been closed by now. Let me check.

**Comment by 0pdd** [comment]
The puzzle `179-c7050a34` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@bkuzmic The problem was with [this new](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/Volumes.java#L36) puzzle. Pay attention to the indentation, if there are multiple lines, lines 2,3,..,n need to start with a space, like this:

```
@todo #12:30min This is a puzzle
 with multiple lines
 that start with a spage (the first letter is at the same column with the ``t``, after the ``@``)
```

Otherwise, 0pdd cannot parse the puzzle and it crashes :D

**Comment by 0crat** [comment]
The job [#205](https://github.com/amihaiemil/docker-java-api/issues/205) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by bkuzmic** [comment]
@amihaiemil Thanks for the tip about puzzles.
