### ISSUE TITLE
Volumes.java:34: Continue implementing prune volumes...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#206]
The puzzle `180-9bad4f6c` from #180 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/5a8ab3e28f16be28a57f8be1044416450b22f765/src/main/java/com/amihaiemil/docker/Volumes.java#L34-L34

The puzzle was created by Boris Kuzmic on 06-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#206](https://github.com/amihaiemil/docker-java-api/issues/206) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/027988ae-dbb0-4b60-b3cf-98f5980bdfeb); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `180-9bad4f6c` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#206](https://github.com/amihaiemil/docker-java-api/issues/206) is now out of scope
