### ISSUE TITLE
Volumes.java:36-38: Extend create with options to specify...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#213]
The puzzle `183-9aed8aaf` from #183 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/9c93ecb0388292848f4a77b4c7d76dcb1fa11d81/src/main/java/com/amihaiemil/docker/Volumes.java#L36-L38

The puzzle was created by Boris Kuzmic on 10-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#213](https://github.com/amihaiemil/docker-java-api/issues/213) assigned to @sbespalov[/z](https://www.0crat.com/u/sbespalov), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/6ddf99f6-2757-4cc3-b3ab-fdfd5d8dbedd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@sbespalov[/z](https://www.0crat.com/u/sbespalov) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The job [#213](https://github.com/amihaiemil/docker-java-api/issues/213) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/02206b8f-929f-4763-851e-d5ef502ca17c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#213` already assigned to @bkuzmic, can't assign to @bkuzmic

**Comment by 0pdd** [comment]
The puzzle `183-9aed8aaf` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#213](https://github.com/amihaiemil/docker-java-api/issues/213) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
