### ISSUE TITLE
Plugins.java:34-36: Continue implementing Plugins API...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#221]
The puzzle `208-b6677773` from #208 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/8a229a28cbc249f3501ab7899ce7904a8404ef60/src/main/java/com/amihaiemil/docker/Plugins.java#L34-L36

The puzzle was created by Boris Kuzmic on 14-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#221](https://github.com/amihaiemil/docker-java-api/issues/221) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#221](https://github.com/amihaiemil/docker-java-api/issues/221) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/c3ea7a5e-7493-4f30-b5b0-b74d2a103a65); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by bkuzmic** [comment]
@0crat wait for #233 review

**Comment by 0crat** [comment]
> @0crat wait for #233 review ([here](https://github.com/amihaiemil/docker-java-api/issues/221#issuecomment-450146335))

@bkuzmic The impediment for [#221](https://github.com/amihaiemil/docker-java-api/issues/221) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0pdd** [comment]
The puzzle `208-b6677773` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#221](https://github.com/amihaiemil/docker-java-api/issues/221) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
