### ISSUE TITLE
ListedNetworks.java:36-37: Implement ListedNetworks...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#226]
The puzzle `211-924fe80a` from #211 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/970d39ca7e752938d6dd9a387a7eaa1f3027b045/src/main/java/com/amihaiemil/docker/ListedNetworks.java#L36-L37

The puzzle was created by Boris Kuzmic on 17-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#226](https://github.com/amihaiemil/docker-java-api/issues/226) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#226](https://github.com/amihaiemil/docker-java-api/issues/226) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/95d5ad35-dd0c-41cb-b46d-ac0e122b3d00); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `211-924fe80a` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#226](https://github.com/amihaiemil/docker-java-api/issues/226) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
