### ISSUE TITLE
RtDocker.java:35-36: Implement RemoteDocker which will...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#23]
The puzzle `11-6dd03fe4` from #11 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/99be189e2f1799427d836fe3077af433955d226f/src/main/java/com/amihaiemil/docker/RtDocker.java#L35-L36

The puzzle was created by Mihai Andronache on 04-Feb-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I can help you index your Github-hosted website, provided that the repository name respects the format ``owner.github.io`` (or has a ``gh-pages`` branch) and the command is given by the repo's owner.

More on commands [here](http://charles.amihaiemil.com/doc.html#commands).
Also, [this](http://www.amihaiemil.com/2017/05/23/meet-charles-michael.html) blog post might be useful.

**Comment by 0crat** [comment]
The job [#23](https://github.com/amihaiemil/docker-java-api/issues/23) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/801518249); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by llorllale** [comment]
@amihaiemil shouldn't this be `v1.30` instead of:

https://github.com/amihaiemil/docker-java-api/blob/c82d0561e0701bdad9e95bd88e8b4c5d2207f832/src/main/java/com/amihaiemil/docker/LocalDocker.java#L56

**Comment by amihaiemil** [comment]
@llorllale no, ``1.35`` is fine. When I checked, that was the latest version.

**Comment by amihaiemil** [comment]
@llorllale the doc we were using is a bit older, that's it. We should search for the newest one; luckily, we did not implement a lot of it yet.

But, for instance, this is the reason why we expose raw JsonObjects -- we let the clinet figure out the payload they have to provide or receive, since they have to know those endpoints anyway, in order to properly build a POJO (if we were to provide such models). 

It makes no sense for a library to struggle with the I/O models of the API, I believe. Then, when the API changes, we must take care to also change our models.

**Comment by 0pdd** [comment]
The puzzle `11-6dd03fe4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#67](https://github.com/amihaiemil/docker-java-api/issues/67), [#68](https://github.com/amihaiemil/docker-java-api/issues/68) are still not solved.

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#23](https://github.com/amihaiemil/docker-java-api/issues/23) is now out of scope

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#100](https://github.com/amihaiemil/docker-java-api/issues/100), [#68](https://github.com/amihaiemil/docker-java-api/issues/68) are still not solved; solved: [#67](https://github.com/amihaiemil/docker-java-api/issues/67).
