### ISSUE TITLE
Extend RegistryConfigAuth to support multiple Docker registries

### ISSUE THREAD

**Issue by bkuzmic** [amihaiemil/docker-java-api#230]
Currently RegistryConfigAuth supports adding only one key-value pair. The key is a registry URL, and the value is an auth configuration object, [as described in the authentication section](https://docs.docker.com/engine/api/v1.35/#section/Authentication). 

Refactor RegistryConfigAuth to support adding multiple key-value pairs.  Here is an example of how the Json should be structured:

```
{
  "docker.example.com": {
    "username": "janedoe",
    "password": "hunter2"
  },
  "https://index.docker.io/v1/": {
    "username": "mobydock",
    "password": "conta1n3rize14"
  }
}
```

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#230](https://github.com/amihaiemil/docker-java-api/issues/230) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0crat** [comment]
The job [#230](https://github.com/amihaiemil/docker-java-api/issues/230) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1d9942bd-f960-4735-b5ad-71b1b7b20ac7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@bkuzmic How methods should work? Which pair should we return on `encoded` method?

**Comment by bkuzmic** [comment]
@paulodamaso Above in the ticket is the example of how the Json should be structured. This Json is then Base64 encoded. One pair is registry url (key) and auth configuration object (value).
In order to support multiple registries and auth config objects, you need to create a constructor that will allow that. One possible implementation is that the constructor can receive a list of objects (call it RegistryAuth) where RegistryAuth class can look like this:

```
class RegistryAuth {
    private final URI registry;
    private final JsonObject data;

    RegistryAuth(final URI registry, final JsonObject data) {
        this.registry = registry;
        this.data = data;
    }

    void addAsJson(final JsonObjectBuilder builder) {
         builder.add(this.registry.toString(), this.data);
    }
}

```

**Comment by paulodamaso** [comment]
@bkuzmic Now I've got confused: shouldn't we use a `Map<URL, Supplier<String>>` for storing those registries? And then, when we would execute the encoded method, we should pass which URL we want. WDTY?

**Comment by bkuzmic** [comment]
@paulodamaso You could use Map (this is probably something amihaiemil would prefer :)).
Encoded method must encode all the available registries. In the example above you have two registries: `docker.example.com` and `https://index.docker.io/v1/` and the result of the encoded method is Base64 of complete Json.

**Comment by paulodamaso** [comment]
@0crat wait for #247 review

**Comment by 0crat** [comment]
> @0crat wait for #247 review ([here](https://github.com/amihaiemil/docker-java-api/issues/230#issuecomment-450129172))

@paulodamaso The impediment for [#230](https://github.com/amihaiemil/docker-java-api/issues/230) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@bkuzmic Merged, please take a look

**Comment by paulodamaso** [comment]
@bkuzmic ping

**Comment by bkuzmic** [comment]
@paulodamaso Thanks. I'll close the issue now.

**Comment by 0crat** [comment]
The job [#230](https://github.com/amihaiemil/docker-java-api/issues/230) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
