### ISSUE TITLE
Network.java:38-41: Implement Network methods: inspect,...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#236]
The puzzle `225-64e49112` from #225 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/073e8158fe18a1b09b991ed09bd2ae05b20f423a/src/main/java/com/amihaiemil/docker/Network.java#L38-L41

The puzzle was created by Paulo Lobo on 18-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#236](https://github.com/amihaiemil/docker-java-api/issues/236) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment]
@0crat wait for #245 review

**Comment by amihaiemil** [comment]
@paulodamaso You left the puzzle in the code. Is it intentional or it can be removed/altered?

**Comment by 0pdd** [comment]
The puzzle `225-64e49112` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#236](https://github.com/amihaiemil/docker-java-api/issues/236) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
