### ISSUE TITLE
ListedNetworks.java:39-41: Implement ListedNetworks...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#237]
The puzzle `226-beabec1e` from #226 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/0fc9dcda03195e37beb0c92b5d5e25a0397daf8c/src/main/java/com/amihaiemil/docker/ListedNetworks.java#L39-L41

The puzzle was created by Paulo Lobo on 18-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#237](https://github.com/amihaiemil/docker-java-api/issues/237) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#237](https://github.com/amihaiemil/docker-java-api/issues/237) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1d3302c6-059d-4210-b66c-bbe74221f7ed); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@bkuzmic[/z](https://www.0crat.com/u/bkuzmic) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by bkuzmic** [comment]
@0crat wait for #246 review

**Comment by 0crat** [comment]
> @0crat wait for #246 review ([here](https://github.com/amihaiemil/docker-java-api/issues/237#issuecomment-450146775))

@bkuzmic The impediment for [#237](https://github.com/amihaiemil/docker-java-api/issues/237) was registered successfully by @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)

**Comment by 0pdd** [comment]
The puzzle `226-beabec1e` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#237](https://github.com/amihaiemil/docker-java-api/issues/237) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
