### ISSUE TITLE
UncheckedUriBuilder.java:73-74: Finish FilteredUriBuilder...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#243]
The puzzle `240-9a51919f` from #240 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/149435f6095e66d304b18443f2a5f5570ebe67a6/src/main/java/com/amihaiemil/docker/UncheckedUriBuilder.java#L73-L74

The puzzle was created by Paulo Lobo on 24-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#243](https://github.com/amihaiemil/docker-java-api/issues/243) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#243](https://github.com/amihaiemil/docker-java-api/issues/243) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/15ff4102-88f1-411f-adca-71ecc1b1ed4c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#243` already assigned to @bkuzmic, can't assign to @bkuzmic

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#243` already assigned to @bkuzmic, can't assign to @bkuzmic

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#243` already assigned to @bkuzmic, can't assign to @bkuzmic

**Comment by 0pdd** [comment]
The puzzle `240-9a51919f` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
Job was finished in 24 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#243](https://github.com/amihaiemil/docker-java-api/issues/243) is now out of scope
