### ISSUE TITLE
LocalDockerITCase.java:42-46: Fix Volumes object return...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#252]
The puzzle `241-dc39c29f` from #241 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/df0c1bc2dd0f7672e494698971faf65a183642a3/src/test/java/com/amihaiemil/docker/LocalDockerITCase.java#L42-L46

The puzzle was created by Paulo Lobo on 27-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#252](https://github.com/amihaiemil/docker-java-api/issues/252) is now in scope, role is `DEV`

**Comment by paulodamaso** [comment]
@0crat refuse, I can't run these tests in windows

**Comment by 0crat** [comment]
> @0crat refuse, I can't run these tests in windows ([here](https://github.com/amihaiemil/docker-java-api/issues/252#issuecomment-454457905))

@paulodamaso Can't understand "refuse,", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by amihaiemil** [comment]
@0crat refuse

**Comment by amihaiemil** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/amihaiemil/docker-java-api/issues/252#issuecomment-454473516))

@amihaiemil The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#252](https://github.com/amihaiemil/docker-java-api/issues/252), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#252](https://github.com/amihaiemil/docker-java-api/issues/252) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/d10394cb-5a8d-4727-8c74-7aaa323878b9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@0crat boost 6x

**Comment by 0crat** [comment]
> @0crat boost 6x ([here](https://github.com/amihaiemil/docker-java-api/issues/252#issuecomment-454776319))

@amihaiemil Boost 6x was set for [#252](https://github.com/amihaiemil/docker-java-api/issues/252)

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/amihaiemil/docker-java-api/issues/252#issuecomment-454473564))

@amihaiemil The job [#252](https://github.com/amihaiemil/docker-java-api/issues/252) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/544eae9b-c29b-4813-9f1d-eecb25367fbd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@0crat assign @bkuzmic

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
> @0crat assign @bkuzmic ([here](https://github.com/amihaiemil/docker-java-api/issues/252#issuecomment-454787751))

@amihaiemil The job [#252](https://github.com/amihaiemil/docker-java-api/issues/252) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/7dcd24cd-a1d0-42c3-bf17-61afbf447ce8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@0crat[/z](https://www.0crat.com/u/0crat) I see that you unassigned this issue; the order is still assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0pdd** [comment]
The puzzle `241-dc39c29f` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
Job was finished in 19 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#252](https://github.com/amihaiemil/docker-java-api/issues/252) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
