### ISSUE TITLE
RtLogs.java:46-50: Apparently, either stderr or stdout...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#258]
The puzzle `256-b806f1e5` from #256 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/ef61751b7d34d3dc9611570be71eab03d1e10a61/src/main/java/com/amihaiemil/docker/RtLogs.java#L46-L50

The puzzle was created by @amihaiemil on 03-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#258](https://github.com/amihaiemil/docker-java-api/issues/258) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#258](https://github.com/amihaiemil/docker-java-api/issues/258) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/abad68d0-ee5d-4051-b852-4b3dd45a0b06); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `256-b806f1e5` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
