### ISSUE TITLE
Implement Containers API

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#26]
Start implementing the containers api

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#45](https://github.com/amihaiemil/docker-java-api/issues/45) is still not solved.

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#46](https://github.com/amihaiemil/docker-java-api/issues/46) is still not solved.

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#47](https://github.com/amihaiemil/docker-java-api/issues/47) is still not solved.

**Comment by 0pdd** [comment]
@amihaiemil 4 puzzles [#45](https://github.com/amihaiemil/docker-java-api/issues/45), [#46](https://github.com/amihaiemil/docker-java-api/issues/46), [#53](https://github.com/amihaiemil/docker-java-api/issues/53), [#54](https://github.com/amihaiemil/docker-java-api/issues/54) are still not solved; solved: [#47](https://github.com/amihaiemil/docker-java-api/issues/47).

**Comment by 0pdd** [comment]
@amihaiemil 5 puzzles [#45](https://github.com/amihaiemil/docker-java-api/issues/45), [#53](https://github.com/amihaiemil/docker-java-api/issues/53), [#54](https://github.com/amihaiemil/docker-java-api/issues/54), [#57](https://github.com/amihaiemil/docker-java-api/issues/57), [#58](https://github.com/amihaiemil/docker-java-api/issues/58) are still not solved; solved: [#46](https://github.com/amihaiemil/docker-java-api/issues/46), [#47](https://github.com/amihaiemil/docker-java-api/issues/47).

**Comment by 0pdd** [comment]
@amihaiemil 4 puzzles [#45](https://github.com/amihaiemil/docker-java-api/issues/45), [#54](https://github.com/amihaiemil/docker-java-api/issues/54), [#57](https://github.com/amihaiemil/docker-java-api/issues/57), [#58](https://github.com/amihaiemil/docker-java-api/issues/58) are still not solved; solved: [#46](https://github.com/amihaiemil/docker-java-api/issues/46), [#47](https://github.com/amihaiemil/docker-java-api/issues/47), [#53](https://github.com/amihaiemil/docker-java-api/issues/53).

**Comment by 0pdd** [comment]
@amihaiemil 3 puzzles [#54](https://github.com/amihaiemil/docker-java-api/issues/54), [#57](https://github.com/amihaiemil/docker-java-api/issues/57), [#58](https://github.com/amihaiemil/docker-java-api/issues/58) are still not solved; solved: [#45](https://github.com/amihaiemil/docker-java-api/issues/45), [#46](https://github.com/amihaiemil/docker-java-api/issues/46), [#47](https://github.com/amihaiemil/docker-java-api/issues/47), [#53](https://github.com/amihaiemil/docker-java-api/issues/53).

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#57](https://github.com/amihaiemil/docker-java-api/issues/57), [#58](https://github.com/amihaiemil/docker-java-api/issues/58) are still not solved; solved: [#45](https://github.com/amihaiemil/docker-java-api/issues/45), [#46](https://github.com/amihaiemil/docker-java-api/issues/46), [#47](https://github.com/amihaiemil/docker-java-api/issues/47), [#53](https://github.com/amihaiemil/docker-java-api/issues/53), [#54](https://github.com/amihaiemil/docker-java-api/issues/54).

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#58](https://github.com/amihaiemil/docker-java-api/issues/58), [#76](https://github.com/amihaiemil/docker-java-api/issues/76) are still not solved; solved: [#45](https://github.com/amihaiemil/docker-java-api/issues/45), [#46](https://github.com/amihaiemil/docker-java-api/issues/46), [#47](https://github.com/amihaiemil/docker-java-api/issues/47), [#53](https://github.com/amihaiemil/docker-java-api/issues/53), [#54](https://github.com/amihaiemil/docker-java-api/issues/54), [#57](https://github.com/amihaiemil/docker-java-api/issues/57).

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#58](https://github.com/amihaiemil/docker-java-api/issues/58), [#88](https://github.com/amihaiemil/docker-java-api/issues/88) are still not solved; solved: [#45](https://github.com/amihaiemil/docker-java-api/issues/45), [#46](https://github.com/amihaiemil/docker-java-api/issues/46), [#47](https://github.com/amihaiemil/docker-java-api/issues/47), [#53](https://github.com/amihaiemil/docker-java-api/issues/53), [#54](https://github.com/amihaiemil/docker-java-api/issues/54), [#57](https://github.com/amihaiemil/docker-java-api/issues/57), [#76](https://github.com/amihaiemil/docker-java-api/issues/76).

**Comment by 0pdd** [comment]
@amihaiemil 2 puzzles [#58](https://github.com/amihaiemil/docker-java-api/issues/58), [#97](https://github.com/amihaiemil/docker-java-api/issues/97) are still not solved; solved: [#45](https://github.com/amihaiemil/docker-java-api/issues/45), [#46](https://github.com/amihaiemil/docker-java-api/issues/46), [#47](https://github.com/amihaiemil/docker-java-api/issues/47), [#53](https://github.com/amihaiemil/docker-java-api/issues/53), [#54](https://github.com/amihaiemil/docker-java-api/issues/54), [#57](https://github.com/amihaiemil/docker-java-api/issues/57), [#76](https://github.com/amihaiemil/docker-java-api/issues/76), [#88](https://github.com/amihaiemil/docker-java-api/issues/88).
