### ISSUE TITLE
UserAgentRequestHeader.java:37-40: Replace hardcoded...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#263]
The puzzle `244-6ed263ee` from #244 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/7d5ba49da9fa95d757cedd2e215d1607f8ae8bc3/src/main/java/com/amihaiemil/docker/UserAgentRequestHeader.java#L37-L40

The puzzle was created by Boris Kuzmic on 03-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#263](https://github.com/amihaiemil/docker-java-api/issues/263) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#263](https://github.com/amihaiemil/docker-java-api/issues/263) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/442402d5-4c82-4d9c-8eb9-9884232e0fd6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `244-6ed263ee` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#263](https://github.com/amihaiemil/docker-java-api/issues/263) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
