### ISSUE TITLE
Plugin.java:37-39: Continue implementing rest of the...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#266]
The puzzle `251-3182eb87` from #251 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/9920ccd170f43e675ffe17a7bea86f0b349c64dc/src/main/java/com/amihaiemil/docker/Plugin.java#L37-L39

The puzzle was created by Boris Kuzmic on 04-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#266](https://github.com/amihaiemil/docker-java-api/issues/266) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#266](https://github.com/amihaiemil/docker-java-api/issues/266) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/bdf0ff2f-260f-4396-9ba8-c5f209b526dd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `251-3182eb87` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#266](https://github.com/amihaiemil/docker-java-api/issues/266) is now out of scope
