### ISSUE TITLE
RtPluginTestCase.java:47-49: Implement Plugin#enable and...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#269]
The puzzle `266-a7f3093d` from #266 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/b6debd0aa281e881585915f0309a5592183f5372/src/test/java/com/amihaiemil/docker/RtPluginTestCase.java#L47-L49

The puzzle was created by Paulo Lobo on 04-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#269](https://github.com/amihaiemil/docker-java-api/issues/269) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#269](https://github.com/amihaiemil/docker-java-api/issues/269) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/e330ebbf-c958-4b35-9097-4b49aa88d9d4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `266-a7f3093d` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
Job was finished in 46 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
