### ISSUE TITLE
Switch to Apache HTTPClient

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#27]
Although not as object-oriented as jcabi-http, we need the apache client since it can support both Unix and TCP sockets + it offers clientside SSL encryption, which jcabi-http lacks.

**Comment by 0pdd** [comment]
@amihaiemil the puzzle [#36](https://github.com/amihaiemil/docker-java-api/issues/36) is still not solved.

**Comment by 0pdd** [comment]
@amihaiemil all 3 puzzles are solved here: [#32](https://github.com/amihaiemil/docker-java-api/issues/32), [#36](https://github.com/amihaiemil/docker-java-api/issues/36), [#29](https://github.com/amihaiemil/docker-java-api/issues/29).
