### ISSUE TITLE
New year, change copyright headers

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#275]
All headers should go from ``2018`` to ``2018-2019``. I would use ``grep/sed`` to change them all in one shot.

**Comment by 0crat** [comment]
Job [#275](https://github.com/amihaiemil/docker-java-api/issues/275) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#275](https://github.com/amihaiemil/docker-java-api/issues/275) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/d0525e44-3a36-4aca-a797-4e2fb859dd8f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 22 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#275](https://github.com/amihaiemil/docker-java-api/issues/275) is now out of scope
