### ISSUE TITLE
Images.java:43-46: Implement importImage method and...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#276]
The puzzle `254-a138a3f9` from #254 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/ed486797221b5598338ad9ae031bc38ae2e89048/src/main/java/com/amihaiemil/docker/Images.java#L43-L46

The puzzle was created by @amihaiemil on 08-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#276](https://github.com/amihaiemil/docker-java-api/issues/276) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#276](https://github.com/amihaiemil/docker-java-api/issues/276) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/4f213a44-9722-444f-9df5-5860d3886de3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `254-a138a3f9` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#276](https://github.com/amihaiemil/docker-java-api/issues/276) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
