### ISSUE TITLE
Images.java:47-49: ImportFromTar method should return...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#277]
The puzzle `254-cfdd63b2` from #254 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/ed486797221b5598338ad9ae031bc38ae2e89048/src/main/java/com/amihaiemil/docker/Images.java#L47-L49

The puzzle was created by @amihaiemil on 08-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#277](https://github.com/amihaiemil/docker-java-api/issues/277) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#277](https://github.com/amihaiemil/docker-java-api/issues/277) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/4ea836c4-49d3-427c-bc25-ef9e3c4b9ebf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#277` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by bkuzmic** [comment]
@amihaiemil I've looked at the method again on (https://docs.docker.com/engine/api/v1.35/#operation/ImageLoad) and it is for importing multiple images at once, using tar file. So, you will need to have a return type `Iterator<Image> `. Also, I guess the only way to know image names is to extract the tar file locally and read contents of `repositories` file. Another way would be to force the user to explicitly provide list of names as another parameter of the method.

**Comment by 0pdd** [comment]
The puzzle `254-cfdd63b2` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
The job [#277](https://github.com/amihaiemil/docker-java-api/issues/277) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)
