### ISSUE TITLE
RtPluginTestCase.java:55-56: Extract method...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#283]
The puzzle `266-4b137964` from #266 has to be resolved: 

https://github.com/amihaiemil/docker-java-api/blob/1968fbabdcd774600be253b1ecd0b173daba56e8/src/test/java/com/amihaiemil/docker/RtPluginTestCase.java#L55-L56

The puzzle was created by Boris Kuzmic on 08-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#283](https://github.com/amihaiemil/docker-java-api/issues/283) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#283](https://github.com/amihaiemil/docker-java-api/issues/283) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/9c7eba63-96f5-4b8d-a985-ff73e5b7a2a4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `266-4b137964` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by 0crat** [comment]
Job was finished in 45 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#283](https://github.com/amihaiemil/docker-java-api/issues/283) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
