### ISSUE TITLE
test for 0crat

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#285]
let's see if 0crat adds issues with only the ``pdd`` label to scope

**Comment by amihaiemil** [comment]
@0crat ping

**Comment by 0crat** [comment]
> @0crat ping ([here](https://github.com/amihaiemil/docker-java-api/issues/285#issuecomment-452690083))

@amihaiemil Can't understand "ping", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/amihaiemil/docker-java-api/issues/285#issuecomment-452696185))

@amihaiemil Job `gh:amihaiemil/docker-java-api#285` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/amihaiemil/docker-java-api/issues/285#issuecomment-452696185))

@amihaiemil The job [#285](https://github.com/amihaiemil/docker-java-api/issues/285) is now out of scope

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#285` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
