### ISSUE TITLE
Closer to Java 9: add Automatic-Module-Name

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#287]
Let's add ``Automatic-Module-Name`` into the Manifest.MF file, via ``maven-jar-plugin`` ``<configuration`` tag:

```xml
<configuration>
    <archive>
        <manifestEntries>
            <Automatic-Module-Name>com.amihaiemil.docker</Automatic-Module-Name>
        </manifestEntries>
    </archive>
</configuration>
```

Source [here](https://blog.frankel.ch/hard-look-state-java-modularization/).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#287](https://github.com/amihaiemil/docker-java-api/issues/287) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1b03a6bd-9f60-4a96-a0d7-5f41219871c6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job was finished in 39 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#287](https://github.com/amihaiemil/docker-java-api/issues/287) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic)
