### ISSUE TITLE
Support for Docker Event System

### ISSUE THREAD

**Issue by thatsIch** [amihaiemil/docker-java-api#296]
Docker enables to listen to its own Event-System by levering the `docker events [Options]` cli-command.
That way you can listen to specific events in your own application like `create` or `health_status`. This allows reacting to a specific event without polling and parsing the `docker events` yourself.

Example implementation in other libraries are

* https://github.com/docker-java/docker-java/blob/master/src/main/java/com/github/dockerjava/api/command/EventsCmd.java and 
* https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/EventStream.java
--

Documentation: https://docs.docker.com/engine/reference/commandline/events/

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@thatsich[/z](https://www.0crat.com/u/thatsich) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@thatsIch Thanks for the ticket! I will have a look over it these next few days :)

**Comment by 0crat** [comment]
Job [#296](https://github.com/amihaiemil/docker-java-api/issues/296) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @thatsich[/z](https://www.0crat.com/u/thatsich)! If you would be a member of [the project](https://www.0crat.com/p/G6LPQQV2P), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by amihaiemil** [comment]
@rultor release it, tag is `0.0.10`

**Comment by amihaiemil** [comment]
@thatsIch I just released version ``0.0.10``, with a first sketch of the functionality. Please, try it, see if it works: 

```java
final Docker docker = new LocalDocker(...);
final Reader events = docker.system().events();
```

The Reader should read the streamed events, which are in Json format, as explained here:
https://docs.docker.com/engine/api/v1.37/#operation/SystemEvents

**Comment by thatsIch** [comment]
Thanks! I will take a look at it tomorrow

**Comment by thatsIch** [comment]
Since windows version of docker does [not support unix sockets](https://github.com/moby/moby/issues/36442) and the suggested [npipe protocol nor tcp protocol] (https://docs.docker.com/docker-for-windows/faqs/#/how-do-i-connect-to-the-remote-docker-engine-api) is apparently not supported by apache http component, I cannot test it at home.

Is there some other way to test it on windows?

**Comment by amihaiemil** [comment]
@thatsIch 

> tcp protocol  is apparently not supported by apache http component

Are you sure? I think it should work fine if you specify the localhost URL with ``http://``. In order to do that, you must use the ``RemoteDocket`` constructor which expects an ``HttpClient``:

> Is there some other way to test it on windows?
There is no other particular way of testing on Windows.

**Comment by amihaiemil** [comment]
@thatsIch don't bother with it yet, I did some tests and it doesn't work. I'll have to release it again, but it's a bit more complex (I currently have no idea how to consume a Stream via HttpClient...). 

I'll continue to look over it but, if you are in a hurry, you can try to make the request yourself, like this:

```java
final Docker docker = new LocalDocker(
    new File("/var/run/docker.sock")
);
final HttpClient client = docker.httpClient();//already configured to work over the unix socket
final HttpGet get = new HttpGet("unix://localhost:80/1.37/events");
this.client.execute(get,...);
```

If you do it and manage to get it working, I'd appreciate a PR :)

**Comment by thatsIch** [comment]
Just to clarify; I get this stacktrace while calling it

<details>
 <summary>Stacktrace</summary>
<pre>
Exception in thread "main" java.lang.UnsatisfiedLinkError: The specified procedure could not be found
	at jnr.ffi.provider.jffi.AsmRuntime.newUnsatisifiedLinkError(AsmRuntime.java:40)
	at jnr.unixsocket.Native$LibC$jnr$ffi$0.socket(Unknown Source)
	at jnr.unixsocket.Native.socket(Native.java:92)
	at jnr.unixsocket.UnixSocketChannel.<init>(UnixSocketChannel.java:101)
	at jnr.unixsocket.UnixSocketChannel.open(UnixSocketChannel.java:60)
	at com.amihaiemil.docker.UnixSocketFactory.createSocket(UnixSocketFactory.java:62)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:119)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:221)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at com.amihaiemil.docker.HttpClientEnvelope.execute(HttpClientEnvelope.java:103)
	at Main.main(Main.java:25)
</pre>
</details>


I just checked the code of Spotify which is using [`npipe`](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/DockerHost.java#L64) . That puzzled me a bit. Maybe the error is something else. It seems using `npipe` is supported via the [`NpipeSocketConnectionFactory`](https://github.com/spotify/docker-client/blob/master/src/main/java/com/spotify/docker/client/npipe/NpipeConnectionSocketFactory.java).

**Comment by amihaiemil** [comment]
@thatsIch I don't really know about what docker-client is doing with npipe -- I actually started writing my own version because I thought theirs was of really poor quality :)

**Comment by 0crat** [comment]
The job [#296](https://github.com/amihaiemil/docker-java-api/issues/296) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/295c79f2-4f88-466c-a2d3-033f07554c07); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@thatsIch It's not implemented, although not working at the moment. We'll continue the fix for it in #299. Closing this now, thanks!

**Comment by 0crat** [comment]
The job [#296](https://github.com/amihaiemil/docker-java-api/issues/296) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)
