### ISSUE TITLE
docker.events() not working

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#299]
The call to docker.events() just halts and waits indefinetely. The reading of the response is probably not done correctly. Let's try to fix it.

**Comment by 0crat** [comment]
Job [#299](https://github.com/amihaiemil/docker-java-api/issues/299) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#299](https://github.com/amihaiemil/docker-java-api/issues/299) assigned to @bkuzmic[/z](https://www.0crat.com/u/bkuzmic), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/0bbe9357-d0b1-4cac-b1c0-14bb18d9972e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by amihaiemil** [comment]
@rultor deploy test

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) not enough funds available in the project, can't set budget of job [#299](https://github.com/amihaiemil/docker-java-api/issues/299), see [§21](http://www.zerocracy.com/policy.html#21); @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#299](https://github.com/amihaiemil/docker-java-api/issues/299), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by amihaiemil** [comment]
* TODO: return a Stream of Event, rather than raw JsonObject

* TODO Add more integration tests.
