### ISSUE TITLE
MatchStatus -> MatchStati

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#301]
This class should be able to check more stati, not only one, and take handle corresponding ResponseHandlers for each of them.

**Comment by 0crat** [comment]
Job [#301](https://github.com/amihaiemil/docker-java-api/issues/301) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#301](https://github.com/amihaiemil/docker-java-api/issues/301) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/fd7a5d12-1469-410b-83d3-6466d9781f53); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#301](https://github.com/amihaiemil/docker-java-api/issues/301), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by maviteixeira** [comment]
Should we close the issue based on this PR ?
https://github.com/amihaiemil/docker-java-api/pull/308

@amihaiemil

**Comment by amihaiemil** [comment]
@maviteixeira yes. let me just assign it to you first, so you get the reputation for it..

**Comment by amihaiemil** [comment]
@0crat assign @maviteixeira

**Comment by 0crat** [comment]
> @0crat assign @maviteixeira ([here](https://github.com/amihaiemil/docker-java-api/issues/301#issuecomment-536884213))

@amihaiemil The job [#301](https://github.com/amihaiemil/docker-java-api/issues/301) assigned to @maviteixeira[/z](https://www.0crat.com/u/maviteixeira), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/e0c5d6fb-4f34-4d02-a5e5-97a3c0a37c9d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @maviteixeira[/z](https://www.0crat.com/u/maviteixeira) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#301](https://github.com/amihaiemil/docker-java-api/issues/301) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @maviteixeira[/z](https://www.0crat.com/u/maviteixeira)
