### ISSUE TITLE
Some Itcases need a ubuntu:latest image to pass

### ISSUE THREAD

**Issue by maviteixeira** [amihaiemil/docker-java-api#303]
In order to pass all the tests from the RtContainerITCase class you need to have ubuntu:latest pulled in your computer, I think would be nice to have this explicitly in the Readme file.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@maviteixeira[/z](https://www.0crat.com/u/maviteixeira) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by maviteixeira** [comment]
The PR is already merged, should I close it ? @amihaiemil

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#303` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
