### ISSUE TITLE
Pull image

### ISSUE THREAD

**Issue by GTP95** [amihaiemil/docker-java-api#307]
Hello,
I'm trying to use your API to pull images from Docker Hub and then inspect them. Based upon the methods' names I think that the way to pull an image should be like:
`final Docker docker = new LocalDocker(
                new File("/var/run/docker.sock")
        );
        docker.images().pull();` 
but I see that the pull method takes two String arguments named "s" and "s1" and I don't understand what they should be nor I found relevant info in the wiki. One should be the image name, but the other? Maybe the website to pull the image from? Or a tag identifying the image among the different possibilities?
Thanks for your help

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@gtp95[/z](https://www.0crat.com/u/gtp95) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by amihaiemil** [comment]
@GTP95 that method expects the name of the image and its tag (see [here](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/RtImages.java#L81)). 

All the classes and methods have javadocs on them, don't forget to download the sources and javadocs as well, in your IDE. Then, you will also see the parameters with meaningful names, not just s1 and s2.

Ler me know if it works :D.

**Comment by GTP95** [comment]
Thanks for your quick answer, I suggest to mention the presence of the javadocs in the wiki. I've implemented another way to obtain what I need but in case I will need again something to interrogate docker from a Java application I will for sure try again with your API ;)

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#307` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
