### ISSUE TITLE
Add abstraction for Engine, Registry and Template APIs

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#310]
At the moment the ``Docker`` interface represents only the ``Engine`` API, yet Docker also offers ``Registry`` and ``Template`` APIs. See [here](https://docs.docker.com/registry/spec/api/).

We should make the ``Docker`` interface more abstract. It should offer 3 methods:

```java
public interface Docker {
    Engine engine();
    Registry registry(); 
    Template template();
}
```

All the methods that are currently on the ``Docker`` interface should be moved on the ``Engine`` interface.

**Comment by amihaiemil** [comment]
N/A

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#310` is not assigned, can't get performer
