### ISSUE TITLE
Please add xml language to code block in Readme

### ISSUE THREAD

**Issue by Guseyn** [amihaiemil/docker-java-api#314]

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@guseyn[/z](https://www.0crat.com/u/guseyn) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
The job [#314](https://github.com/amihaiemil/docker-java-api/issues/314) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/28765164-dfab-4f25-a75d-b0a9f2ef132d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @guseyn[/z](https://www.0crat.com/u/guseyn)

**Comment by amihaiemil** [comment]
@Guseyn fixed, see https://github.com/amihaiemil/docker-java-api/commit/c1d0c053fa89e178bf8ada716d0159e1145ce68b

Now, please close this ticket. You are the author, the PM will complain if I close it :)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)
