### ISSUE TITLE
401 Unauthorized when trying to Deploy to Nexus

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#318]
Let's try to fix this

**Comment by amihaiemil** [comment]
first, update and reencrypt the settings.xml with the new pwd

**Comment by amihaiemil** [comment]
fixed

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#318` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
