### ISSUE TITLE
UnixHttpClient.java:47-48: Implement a...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#32]
The puzzle `29-9f250f40` from #29 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/64b03124fa03420a9972d7ab5b89051d7b125e8b/src/main/java/com/amihaiemil/docker/UnixHttpClient.java#L47-L48

The puzzle was created by amihaiemil on 24-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by amihaiemil** [comment]
@0crat assign @amihaiemil

**Comment by 0pdd** [comment]
The puzzle `29-9f250f40` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#36](https://github.com/amihaiemil/docker-java-api/issues/36) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the last puzzle [#36](https://github.com/amihaiemil/docker-java-api/issues/36) is solved here.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
