### ISSUE TITLE
Rename LocalDocker and RemoteDocker

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#323]
These classes should be renamed as they are a bit confusing especially for Windows users. 

LocalDocker is actually meant for communication over a UNIX Socket (the "local docker", but actually only in UNIX Environments)

RemoteDocker is meant for communication over HTTP (normal TCP/IP). This class can be used both on Unix and Windows. Futhermore, this class should actually always be used on Windows and, when Docker is local, the URL should be localhost...

Suggested renamings:

LocalDocker     -> LocalUnixDocker
RemoteDocker -> RemoteTcpDocker

**Comment by amihaiemil** [comment]
fixed in #328

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#323` is not assigned, can't get performer
