### ISSUE TITLE
test

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#33]
test for zc

**Comment by amihaiemil** [comment]
@0crat hello

**Comment by amihaiemil** [comment]
@0crat hello

**Comment by 0crat** [comment]
> @0crat hello ([here](https://github.com/amihaiemil/docker-java-api/issues/33#issuecomment-371420412))

@amihaiemil Hey, what's up, how is it going?

**Comment by amihaiemil** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/amihaiemil/docker-java-api/issues/33#issuecomment-371420725))

@amihaiemil Job [#33](https://github.com/amihaiemil/docker-java-api/issues/33) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#33](https://github.com/amihaiemil/docker-java-api/issues/33) is now out of scope
