### ISSUE TITLE
Test2

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#34]
Test

**Comment by 0crat** [comment]
Job [#34](https://github.com/amihaiemil/docker-java-api/issues/34) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#34](https://github.com/amihaiemil/docker-java-api/issues/34) is now out of scope
