### ISSUE TITLE
First Issue For Zoe

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#357]
Zoe should automatically register this Issue as a Task and find an assignee.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#357` is not assigned, can't get performer

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by amihaiemil** [comment]
@charlesmike hello

**Comment by charlesmike** [comment]
> @charlesmike hello

Hi @amihaiemil! I'm the Project Manager of this project. I take care of Issues' assignments, payments and more.Want me to work for your project too? Go [here](https://self-xdsd.com). 

I work primarily at Github, but I'll also start working at GitLab and BitBucket soon.

**Comment by amihaiemil** [comment]
@charlesmike status

**Comment by charlesmike** [comment]
> @charlesmike status

@amihaiemil this ticket is not registered as a task, therefore I'm not working on itat the moment.

If you want me to take care of it, assign it to me or say "register".

**Comment by amihaiemil** [comment]
@charlesmike status

**Comment by amihaiemil** [comment]
@charlesmike status

**Comment by charlesmike** [comment]
> @charlesmike status

@amihaiemil this ticket is not registered as a task, therefore I'm not working on itat the moment.

If you want me to take care of it, assign it to me or say "register".
