### ISSUE TITLE
Second Issue for Zoe

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#358]
Second one for test.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#358` is not assigned, can't get performer

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-09T14:13:16.828241``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partiallyand leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by 0crat** [comment]
You @charlesmike[/z](https://www.0crat.com/u/charlesmike) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#358` is not assigned, can't get performer

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
