### ISSUE TITLE
Find more contributors here

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#359]
Let's try to find more contributors

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-09T14:23:13.109253``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partiallyand leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@criske 
![image](https://user-images.githubusercontent.com/6305156/94552738-05a8da00-0260-11eb-8006-4a191c379320.png)

**Comment by criske** [comment]
@amihaiemil 👍  :D

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#359` is not assigned, can't get performer

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
