### ISSUE TITLE
RtDocker.java:39-41: Reimplement ping() with the new...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#36]
The puzzle `32-472ade5c` from #32 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/508e1d092e7611afbfc57e60e3e9ee7331690c37/src/main/java/com/amihaiemil/docker/RtDocker.java#L39-L41

The puzzle was created by amihaiemil on 11-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/start_order.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation[582] groovy.lang.GroovyRuntimeException: Cannot compare com.jcabi.xml.ListWrapper with value '[gh:zerocracy/farm#220, gh:zerocracy/farm#435, gh:zerocracy/farm#416, gh:zerocracy/farm#497, gh:zerocracy/farm#512, gh:zerocracy/farm#415, gh:zerocracy/farm#422, gh:zerocracy/farm#528]' and java.lang.Integer with value '32'
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/amihaiemil/docker-java-api/issues/36#issuecomment-372136590))

@amihaiemil This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#36](https://github.com/amihaiemil/docker-java-api/issues/36) is [in scope](http://www.zerocracy.com/policy.html#14) for 3min
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/G6LPQQV2P?q=%7Bjob%3A%27gh%3Aamihaiemil%2Fdocker-java-api%2336%27%7D) (restricted area)

**Comment by amihaiemil** [comment]
@0crat assign @amihaiemil

**Comment by 0crat** [comment]
> @0crat assign @amihaiemil ([here](https://github.com/amihaiemil/docker-java-api/issues/36#issuecomment-372136660))

@amihaiemil There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/start_order.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation[582] groovy.lang.GroovyRuntimeException: Cannot compare com.jcabi.xml.ListWrapper with value '[gh:zerocracy/farm#220, gh:zerocracy/farm#435, gh:zerocracy/farm#416, gh:zerocracy/farm#497, gh:zerocracy/farm#512, gh:zerocracy/farm#415, gh:zerocracy/farm#422, gh:zerocracy/farm#528]' and java.lang.Integer with value '32'
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0pdd** [comment]
The puzzle `32-472ade5c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#36](https://github.com/amihaiemil/docker-java-api/issues/36) is now out of scope
