### ISSUE TITLE
UnixHttpClientITCase.java: This should be un-ignored and refactored after #41 is done. The unix socket server needs to be spooled up, and the url changed accordingly.

### ISSUE THREAD

**Issue by zoeself** [amihaiemil/docker-java-api#361]
The TODO ``44-50450105`` from #44 has to be resolved:

```
This should be un-ignored and refactored after #41 is done. The unix socket server needs to be spooled up, and the url changed accordingly.
```

It is is located at [src/test/java/com/amihaiemil/docker/UnixHttpClientITCase.java#L49-L51](https://github.com/amihaiemil/docker-java-api/blob/master/src/test/java/com/amihaiemil/docker/UnixHttpClientITCase.java#L49-L51).

It was created by @llorllale on 2018-03-15T21:26:05Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@zoeself thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#361` is not assigned, can't get performer
