### ISSUE TITLE
Swarm.java: Continue implementing the rest of the Swarm operations. See https://docs.docker.com/engine/api/v1.35/#tag/Swarm for reference and also the roadmap laid out here: https://github.com/amihaiemil/docker-java-api/issues/3#issuecomment-375821822

### ISSUE THREAD

**Issue by zoeself** [amihaiemil/docker-java-api#367]
The TODO ``77-48853626`` from #77 has to be resolved:

```
Continue implementing the rest of the Swarm operations. See https://docs.docker.com/engine/api/v1.35/#tag/Swarm for reference and also the roadmap laid out here: https://github.com/amihaiemil/docker-java-api/issues/3#issuecomment-375821822
```

It is is located at [src/main/java/com/amihaiemil/docker/Swarm.java#L40-L43](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/Swarm.java#L40-L43).

It was created by @amihaiemil on 2018-04-25T18:36:35Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@zoeself thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#367` is not assigned, can't get performer
