### ISSUE TITLE
RtLogs.java: Continue implementing this class, take into consideration the query parameters as described here: https://docs.docker.com/engine/api/v1.35/#operation/ContainerLogs Since the class should be immutable, the parameters should come in the ctor and appended to the requests when they are performed. Let's leave this part for v0.0.3 or later, it's not urgent now.

### ISSUE THREAD

**Issue by zoeself** [amihaiemil/docker-java-api#370]
The TODO ``135-7b38f89f`` from #135 has to be resolved:

```
Continue implementing this class, take into consideration the query parameters as described here: https://docs.docker.com/engine/api/v1.35/#operation/ContainerLogs Since the class should be immutable, the parameters should come in the ctor and appended to the requests when they are performed. Let's leave this part for v0.0.3 or later, it's not urgent now.
```

It is is located at [src/main/java/com/amihaiemil/docker/RtLogs.java#L43-L48](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/RtLogs.java#L43-L48).

It was created by @amihaiemil on 2018-06-12T12:54:04Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@zoeself thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#370` is not assigned, can't get performer
