### ISSUE TITLE
RtImagesITCase.java: Add integration tests for fil

### ISSUE THREAD

**Issue by zoeself** [amihaiemil/docker-java-api#372]
The TODO ``153-ba83999e`` from #153 has to be resolved:

```
Add integration tests for filters.
```

It is is located at [src/test/java/com/amihaiemil/docker/RtImagesITCase.java#L42-L42](https://github.com/amihaiemil/docker-java-api/blob/master/src/test/java/com/amihaiemil/docker/RtImagesITCase.java#L42-L42).

It was created by @llorllale on 2018-10-10T01:41:22Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@zoeself thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#372` is not assigned, can't get performer
