### ISSUE TITLE
RtImagesITCase.java: To have multiple controlled i

### ISSUE THREAD

**Issue by zoeself** [amihaiemil/docker-java-api#373]
The TODO ``187-99b12eee`` from #187 has to be resolved:

```
To have multiple controlled images for filtering and not the ubuntu image dependency for this test will be nice to have the build Images implemented as described here: https://docs.docker.com/engine/api/v1.37/#operation/ImageBuild.
```

It is is located at [src/test/java/com/amihaiemil/docker/RtImagesITCase.java#L69-L72](https://github.com/amihaiemil/docker-java-api/blob/master/src/test/java/com/amihaiemil/docker/RtImagesITCase.java#L69-L72).

It was created by Marco Teixeira on 2019-08-17T00:17:16Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@zoeself thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#373` is not assigned, can't get performer
