### ISSUE TITLE
RtLogsITCase.java: Fix the IT case for follow(),

### ISSUE THREAD

**Issue by zoeself** [amihaiemil/docker-java-api#374]
The TODO ``256-2502f853`` from #256 has to be resolved:

```
Fix the IT case for follow(), it is currently failing. We might have to implement the stream decoding (in case TTY is disabled when the Container is created), as explained here, in "Stream format" paragraph: https://docs.docker.com/engine/api/v1.37/#operation/ContainerAttach
```

It is is located at [src/test/java/com/amihaiemil/docker/RtLogsITCase.java#L40-L44](https://github.com/amihaiemil/docker-java-api/blob/master/src/test/java/com/amihaiemil/docker/RtLogsITCase.java#L40-L44).

It was created by @amihaiemil on 2019-01-03T20:27:58Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@zoeself thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#374` is not assigned, can't get performer
