### ISSUE TITLE
JsonResource.java: Continue making other Json re

### ISSUE THREAD

**Issue by zoeself** [amihaiemil/docker-java-api#376]
The TODO ``114-bb7b9082`` from #114 has to be resolved:

```
Continue making other Json resources from the API (e.g. Image), extend this class, so we can avoid the N+1 query problem. Through this mechanism, each resource holds the JsonObject that was returned by the API at the moment of its creation. If the client would like to make sure that the resource's JsonObject is updated, they should call the inspect() method.
```

It is is located at [src/main/java/com/amihaiemil/docker/JsonResource.java#L45-L50](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/JsonResource.java#L45-L50).

It was created by @amihaiemil on 2018-05-17T10:28:38Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@zoeself thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#376` is not assigned, can't get performer
