### ISSUE TITLE
RtContainer.java: Continue implementing the res

### ISSUE THREAD

**Issue by zoeself** [amihaiemil/docker-java-api#378]
The TODO ``97-657d9f49`` from #97 has to be resolved:

```
Continue implementing the rest of the Container operations (pause, unpause, logs etc) See the Docker API Docs for reference: https://docs.docker.com/engine/api/v1.35/#tag/Container
```

It is is located at [src/main/java/com/amihaiemil/docker/RtContainer.java#L43-L45](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/RtContainer.java#L43-L45).

It was created by @amihaiemil on 2018-05-10T13:26:00Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@zoeself thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#378` is not assigned, can't get performer
