### ISSUE TITLE
Images.java: Add Fake implementations of I

### ISSUE THREAD

**Issue by zoeself** [amihaiemil/docker-java-api#379]
The TODO ``152-6918ce7a`` from #152 has to be resolved:

```
Add Fake implementations of Images and Image, in order to unit test method save() and other future methods which may require more than 1 HTTP request. Currently, the unit testing infrastructure does not support more than 1 HTTP request..
```

It is is located at [src/main/java/com/amihaiemil/docker/Images.java#L39-L42](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/Images.java#L39-L42).

It was created by @amihaiemil on 2018-08-26T08:24:51Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@zoeself thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#379` is not assigned, can't get performer
