### ISSUE TITLE
RtLogs.java: Continue implementing this cl

### ISSUE THREAD

**Issue by zoeself** [amihaiemil/docker-java-api#380]
The TODO ``135-7b38f89f`` from #135 has to be resolved:

```
Continue implementing this class, take into consideration the query parameters as described here: https://docs.docker.com/engine/api/v1.35/#operation/ContainerLogs Since the class should be immutable, the parameters should come in the ctor and appended to the requests when they are performed. Let's leave this part for v0.0.3 or later, it's not urgent now.
```

It is is located at [src/main/java/com/amihaiemil/docker/RtLogs.java#L43-L48](https://github.com/amihaiemil/docker-java-api/blob/master/src/main/java/com/amihaiemil/docker/RtLogs.java#L43-L48).

It was created by @amihaiemil on 2018-06-12T12:54:04Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@zoeself thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil task successfully removed.

**Comment by 0crat** [comment]
Job `gh:amihaiemil/docker-java-api#380` is not assigned, can't get performer

**Comment by charlesmike** [comment]
@zoeself thanks for reopening this, I'll find someone to take a look at it. 
However, please keep in mind that reopening tickets is a bad practice. Next time, please open a new ticket.

**Comment by 0crat** [comment]
Job [#380](https://github.com/amihaiemil/docker-java-api/issues/380) is not in the agenda of @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), can't set title

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
