### ISSUE TITLE
test self pm

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#382]

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-08T11:55:16.247011``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@charlesmike resign

**Comment by charlesmike** [comment]
> @charlesmike resign

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil task successfully removed.

**Comment by 0crat** [comment]
You @charlesmike[/z](https://www.0crat.com/u/charlesmike) need to have one of these roles in order to do "Request order start": `ARC`, `PO`; I'm sorry to say this, but at the moment you've got no roles in this project
