### ISSUE TITLE
Typo in interface Docker

### ISSUE THREAD

**Issue by llorllale** [amihaiemil/docker-java-api#39]
Method `networs` should be `networks`.

**Comment by amihaiemil** [comment]
@llorllale I see, thanks, I'll keep it in mind for the next PR. I won't accept it as a valid Issue because it is a cosmetic matter :D

**Comment by 0pdd** [comment]
@llorllale these puzzles are still not solved: [#41](https://github.com/amihaiemil/docker-java-api/issues/41), [#42](https://github.com/amihaiemil/docker-java-api/issues/42).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#41](https://github.com/amihaiemil/docker-java-api/issues/41) is still not solved; solved: [#38](https://github.com/amihaiemil/docker-java-api/issues/38), [#42](https://github.com/amihaiemil/docker-java-api/issues/42).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#87](https://github.com/amihaiemil/docker-java-api/issues/87) is still not solved; solved: [#38](https://github.com/amihaiemil/docker-java-api/issues/38), [#41](https://github.com/amihaiemil/docker-java-api/issues/41), [#42](https://github.com/amihaiemil/docker-java-api/issues/42), [#79](https://github.com/amihaiemil/docker-java-api/issues/79).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#87](https://github.com/amihaiemil/docker-java-api/issues/87) is still not solved; solved: [#10](https://github.com/amihaiemil/docker-java-api/issues/10), [#38](https://github.com/amihaiemil/docker-java-api/issues/38), [#41](https://github.com/amihaiemil/docker-java-api/issues/41), [#42](https://github.com/amihaiemil/docker-java-api/issues/42), [#79](https://github.com/amihaiemil/docker-java-api/issues/79).
