### ISSUE TITLE
AssertRequest.java:52-55: Figure out how to let the user...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#42]
The puzzle `38-1586cf52` from #38 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/23aa92a82f3ee0f8fa258716bfee7fce889872a4/src/test/java/com/amihaiemil/docker/mock/AssertRequest.java#L52-L55

The puzzle was created by George Aristy on 13-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by amihaiemil** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/amihaiemil/docker-java-api/issues/42#issuecomment-372771507))

@amihaiemil Job [#42](https://github.com/amihaiemil/docker-java-api/issues/42) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#42](https://github.com/amihaiemil/docker-java-api/issues/42) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/730533225). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@llorllale I think you can easily solve this by passing some sort of ``Conditions`` object in the ctor. This object would encapsulate that Collection of Predicate and also have a given failure message.

But this is just an idea, do it however you see more fit :D

**Comment by llorllale** [comment]
@amihaiemil honestly, since this is just a support class for our tests I don't want to invest too much in the design. Maybe `Condition` can just be a carrier for a `String` and a `Predicate<HttpRequest>`, no?

**Comment by amihaiemil** [comment]
@llorllale Yes, sure. But also start writing a test class for it and leave puzzlez for testing it if you don't have enough time.

Even though it is a support class, it needs to be tested itself so we are sure it works fine. Otherwise, bugs could be introduced into it and then all tests written with it become unreliable :)

**Comment by 0pdd** [comment]
The puzzle `38-1586cf52` has disappeared from the source code, that's why I closed this issue.

**Comment by amihaiemil** [comment]
@llorllale I know, I also wasn't paid for the closed PRs, as ARC... 

There is a bug in 0crat, discussed here: https://github.com/zerocracy/farm/issues/813
But it should make the payment tomorrow, I think.

**Comment by amihaiemil** [comment]
@llorllale 0crat seems to be online now, did it pay you?

**Comment by llorllale** [comment]
@amihaiemil it paid me yesterday at around 21:45 UTC
