### ISSUE TITLE
RtContainer.java:13-15: This class represents a...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#46]
The puzzle `26-c1e6c3eb` from #26 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/f5a14a642034a8bcde09e708cb5c27564061dfab/src/main/java/com/amihaiemil/docker/RtContainer.java#L13-L15

The puzzle was created by amihaiemil on 13-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#46](https://github.com/amihaiemil/docker-java-api/issues/46) is now in scope, role is `DEV`

**Comment by amihaiemil** [comment]
@0crat assign @amihaiemil

**Comment by 0crat** [comment]
> @0crat assign @amihaiemil ([here](https://github.com/amihaiemil/docker-java-api/issues/46#issuecomment-373636947))

@amihaiemil The job [#46](https://github.com/amihaiemil/docker-java-api/issues/46) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/750831962). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
> @0crat assign @amihaiemil ([here](https://github.com/amihaiemil/docker-java-api/issues/46#issuecomment-373636947))

@amihaiemil Job `gh:amihaiemil/docker-java-api#46` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
> @0crat assign @amihaiemil ([here](https://github.com/amihaiemil/docker-java-api/issues/46#issuecomment-373636947))

@amihaiemil Job `gh:amihaiemil/docker-java-api#46` already assigned to @amihaiemil, can't assign to @amihaiemil

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/amihaiemil/docker-java-api/issues/46#issuecomment-373789011))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#46](https://github.com/amihaiemil/docker-java-api/issues/46) is [in scope](http://www.zerocracy.com/policy.html#14) for 10hr
  * The role is `DEV`
  * The job is assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) for [9hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/G6LPQQV2P?q=%7Bjob%3A%27gh%3Aamihaiemil%2Fdocker-java-api%2346%27%7D) (restricted area)

**Comment by 0pdd** [comment]
The puzzle `26-c1e6c3eb` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#57](https://github.com/amihaiemil/docker-java-api/issues/57), [#58](https://github.com/amihaiemil/docker-java-api/issues/58) are still not solved.

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#46](https://github.com/amihaiemil/docker-java-api/issues/46) is now out of scope

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#58](https://github.com/amihaiemil/docker-java-api/issues/58), [#76](https://github.com/amihaiemil/docker-java-api/issues/76) are still not solved; solved: [#57](https://github.com/amihaiemil/docker-java-api/issues/57).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#58](https://github.com/amihaiemil/docker-java-api/issues/58), [#88](https://github.com/amihaiemil/docker-java-api/issues/88) are still not solved; solved: [#57](https://github.com/amihaiemil/docker-java-api/issues/57), [#76](https://github.com/amihaiemil/docker-java-api/issues/76).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#58](https://github.com/amihaiemil/docker-java-api/issues/58), [#97](https://github.com/amihaiemil/docker-java-api/issues/97) are still not solved; solved: [#57](https://github.com/amihaiemil/docker-java-api/issues/57), [#76](https://github.com/amihaiemil/docker-java-api/issues/76), [#88](https://github.com/amihaiemil/docker-java-api/issues/88).
