### ISSUE TITLE
RtContainersTestCase.java:47-48: Implement tests on the...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#53]
The puzzle `47-15f4a258` from #47 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/7d8c9980f004f50fdc22b2024f97b9253629bcf7/src/test/java/com/amihaiemil/docker/RtContainersTestCase.java#L47-L48

The puzzle was created by George Aristy on 15-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/amihaiemil/docker-java-api/issues/53#issuecomment-373636851))

@amihaiemil Job [#53](https://github.com/amihaiemil/docker-java-api/issues/53) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#53](https://github.com/amihaiemil/docker-java-api/issues/53) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/771866951). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0pdd** [comment]
The puzzle `47-15f4a258` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#53](https://github.com/amihaiemil/docker-java-api/issues/53) is now out of scope
