### ISSUE TITLE
Setup Docker on Travis and/or Rultor 

### ISSUE THREAD

**Issue by amihaiemil** [amihaiemil/docker-java-api#55]
We need this setup in order to run IT cases.

**Comment by 0crat** [comment]
Job [#55](https://github.com/amihaiemil/docker-java-api/issues/55) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#55](https://github.com/amihaiemil/docker-java-api/issues/55) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/771882316). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@amihaiemil this task requires more information/specifications. Docker can definitely be used in Travis (I have), but **what exactly is this task asking us to do?**

**Comment by llorllale** [comment]
@amihaiemil sounds like this job is potentially as simple enabling the docker service in the `.travis.yml` file, see [here](https://docs.travis-ci.com/user/docker/).

I haven't run the integration tests, maybe I can run them and, if they work, I can add a line to the `.travis.yml` file to run them. WDYT?

**Comment by amihaiemil** [comment]
@llorllale Yes, I think that's all we need -- integration tests should work with the docker instalation out of the box, default settings. If you run them locally (well, so far it's only one test for ping haha), they should work fine.

**Comment by llorllale** [comment]
@amihaiemil I'll try it out tonight - I'm on windows right now. `LocalDockerITCase.pingsDocker()` fails on me, probably due to my OS.

**Comment by amihaiemil** [comment]
@llorllale yes, I guess, it's a unix socket behind :D as far as I know, there isn't even Docker for Windows. At least not as easy as for linux, I think you need some tweaks :-?

**Comment by llorllale** [comment]
@amihaiemil on Windows < 10 we have the docker toolbar. From 10 onwards there's "true" docker or something like that

**Comment by amihaiemil** [comment]
@llorllale thanks :)

**Comment by 0crat** [comment]
Order was finished: +30 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#55](https://github.com/amihaiemil/docker-java-api/issues/55) is now out of scope
