### ISSUE TITLE
RtContainer.java:19-21: This class represents a...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#57]
The puzzle `46-f470c157` from #46 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/ca2e586aa4c4550784c893f3ad205def5014f0d1/src/main/java/com/amihaiemil/docker/RtContainer.java#L19-L21

The puzzle was created by amihaiemil on 19-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#57](https://github.com/amihaiemil/docker-java-api/issues/57) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#57](https://github.com/amihaiemil/docker-java-api/issues/57) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/881367938); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat waiting on review for PR #73

**Comment by 0crat** [comment]
> @0crat waiting on review for PR #73 ([here](https://github.com/amihaiemil/docker-java-api/issues/57#issuecomment-378340227))

@llorllale The impediment for [#57](https://github.com/amihaiemil/docker-java-api/issues/57) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `46-f470c157` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#76](https://github.com/amihaiemil/docker-java-api/issues/76) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#88](https://github.com/amihaiemil/docker-java-api/issues/88) is still not solved; solved: [#76](https://github.com/amihaiemil/docker-java-api/issues/76).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#97](https://github.com/amihaiemil/docker-java-api/issues/97) is still not solved; solved: [#76](https://github.com/amihaiemil/docker-java-api/issues/76), [#88](https://github.com/amihaiemil/docker-java-api/issues/88).
