### ISSUE TITLE
RtSwarm.java:42-44: The code for inspect() is essentially...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#72]
The puzzle `3-b7c517df` from #3 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/9abbafd0d62e336e7326c1ee82e1cef7ea1899e2/src/main/java/com/amihaiemil/docker/RtSwarm.java#L42-L44

The puzzle was created by Mihai A on 28-Mar-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#72](https://github.com/amihaiemil/docker-java-api/issues/72) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#72](https://github.com/amihaiemil/docker-java-api/issues/72) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/881376172); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat waiting on review for PR #74

**Comment by 0crat** [comment]
> @0crat waiting on review for PR #74 ([here](https://github.com/amihaiemil/docker-java-api/issues/72#issuecomment-378359335))

@llorllale The impediment for [#72](https://github.com/amihaiemil/docker-java-api/issues/72) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `3-b7c517df` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)
