### ISSUE TITLE
UnixServer.java:132-133: Make the response from this...

### ISSUE THREAD

**Issue by 0pdd** [amihaiemil/docker-java-api#79]
The puzzle `41-7d61f78a` from #41 has to be resolved:

https://github.com/amihaiemil/docker-java-api/blob/096c1903c041cb34193dce178f19cd279b200b5a/src/test/java/com/amihaiemil/docker/mock/UnixServer.java#L132-L133

The puzzle was created by George Aristy on 04-Apr-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/G6LPQQV2P) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#79](https://github.com/amihaiemil/docker-java-api/issues/79) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#79](https://github.com/amihaiemil/docker-java-api/issues/79) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/941386256); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/amihaiemil/docker-java-api/issues/79#issuecomment-381334318))

@llorllale The impediment for [#79](https://github.com/amihaiemil/docker-java-api/issues/79) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `41-7d61f78a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#87](https://github.com/amihaiemil/docker-java-api/issues/87) is still not solved.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#79](https://github.com/amihaiemil/docker-java-api/issues/79) is now out of scope

**Comment by 0pdd** [comment]
@0pdd the puzzle [#87](https://github.com/amihaiemil/docker-java-api/issues/87) is still not solved; solved: [#10](https://github.com/amihaiemil/docker-java-api/issues/10).
