### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by llorllale** [amihaiemil/docker-java-api#93]
(from [this](https://github.com/amihaiemil/docker-java-api/pull/91#issue-184137184) comment)

Example of pattern we keep seeing over and over (taken from `RtContainer.start()`:

```java
    @Override
    public void start() throws IOException {
        final HttpPost start = new HttpPost(
            this.baseUri.toString() + "/start"
        );
        final HttpResponse response = this.client.execute(start);
        final int status = response.getStatusLine().getStatusCode();
        if(status != HttpStatus.SC_NO_CONTENT) {
            throw new UnexpectedResponseException(
                start.getURI().toString(), status, HttpStatus.SC_NO_CONTENT
            );
        }
        start.releaseConnection();
    }
```

The requirements fulfilled by this pattern always seem to be:
* Some sort of *command* sent to the docker api
* Parametrize the `HttpUriRequest` with the URL and as one of the HTTP methods (GET/POST)
* Verify response code against expected value. If no match then throw `UnexpectedResponseException`
* Release the underlying resources tied up by the `HttpUriRequest` object
* We're not expecting to read anything from the response's payload

If the above points hold true then:

**Proposal**
```java
new Action(
    new HttpPost(this.baseUri.toString() + "/start"),
    HttpStatus.SC_NO_CONTENT
).execute();
```

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) please, pay attention to this issue

**Comment by llorllale** [comment]
@amihaiemil implementing/decorating `HttpClient` sounds OK I guess. I just hate the `HttpClient` interface itself :)

My proposal would provide a simple, "SAM"/single-method interface. You decide.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-7
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job [#93](https://github.com/amihaiemil/docker-java-api/issues/93) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/G6LPQQV2P/1222129471); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by amihaiemil** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/amihaiemil/docker-java-api/issues/93#issuecomment-387301003))

@amihaiemil The impediment for [#93](https://github.com/amihaiemil/docker-java-api/issues/93) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@llorllale Yes, I will implement a decorating ``HttpClient`` which will do these repeated checks for us. I don't like the ``SAM`` approach since it is a forced abstraction -- it's like sweeping the dirt under the mat. In general, I don't like using object as functions... that is, wrapping object X in object Y with the sole purpose of doing something with Y punctually, where needed.

I'm not sure if this makes sense, but anyway, something smells bad about it. A good example of this is cactoos's ``LengthOf`` class, which is a strange thing: it is used to wrap a ``Text`` (I think?) and you call method ``value()`` in order to read the text...

**Comment by amihaiemil** [comment]
@llorllale can we close this? :D

**Comment by llorllale** [comment]
@amihaiemil thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#93](https://github.com/amihaiemil/docker-java-api/issues/93) is now out of scope
